iggy/Cargo.toml
When cross compiling it is required to have openssl MUSL
library to compile against. There are 2 ways of fixing it,
this commit introduces easy one, which is using vendored
openssl. Harder way is to create custom docker image with
libssl-dev.
See https://github.com/cross-rs/cross/wiki/Recipes#openssl
=> Fix cross compilation

.github/workflows/rust.yml
It seems like github action needs to have
specified pull request workflow. This commit
sets workflow to act on "closed" and all default
actions.
=> Fix release via github actions

Cargo.lock, server/Cargo.toml, server/src/build.rs, server/src/main.rs
Added printing of relevant build metadata during
startup of iggy-server. This should help debug
problems in the future.
=> Print build metadata during startup

.github/workflows/rust.yml
When PR is updated, cancel ongoing workflow.
This should help to not-waste github workers ;)
=> Improve CI concurrency

server/src/main.rs
Unfortunately, in previous PR (#13) there was mistake done in which compilation env variables and runtime env variables were mixed up. This commit fixes this problem.
=> Fix runtime error when starting docker container

Cargo.lock, cmd/Cargo.toml, cmd/src/args/common.rs, cmd/src/args/mod.rs, cmd/src/args/stream.rs, cmd/src/args/topic.rs, cmd/src/cmd/mod.rs, cmd/src/cmd/stream/list.rs, cmd/src/cmd/topic/create.rs, cmd/src/cmd/topic/delete.rs, cmd/src/cmd/topic/get.rs, cmd/src/cmd/topic/list.rs, cmd/src/cmd/topic/mod.rs, cmd/src/cmd/topic/update.rs, cmd/src/main.rs
Adding set of modules under cmd::topic module which implement topic
specific commands. Adding also args::topic and args::common modules
which contain command line args parser definitions and help messages.
Move stream related command line parser structures to separate module
Update create version to 0.2.0
=> Add topic related commands

Cargo.lock, cmd/Cargo.toml, cmd/src/args/stream.rs, cmd/src/args/topic.rs, cmd/src/cmd/stream/delete.rs, cmd/src/cmd/stream/get.rs, cmd/src/cmd/stream/update.rs, cmd/src/cmd/topic/create.rs, cmd/src/cmd/topic/delete.rs, cmd/src/cmd/topic/get.rs, cmd/src/cmd/topic/list.rs, cmd/src/cmd/topic/update.rs, cmd/src/main.rs, iggy/src/identifier.rs
Replace u32 with Identifier struct in order to enable user to use either stream / topic ID (numerical) or name in command line operations like update, delete, get, list (topics). This fix #71
=> Use Identifier struct for stream and topic identification

Cargo.lock, cmd/Cargo.toml, cmd/src/args/stream.rs, cmd/src/args/topic.rs, cmd/src/cmd/stream/delete.rs, cmd/src/cmd/stream/get.rs, cmd/src/cmd/stream/update.rs, cmd/src/cmd/topic/create.rs, cmd/src/cmd/topic/delete.rs, cmd/src/cmd/topic/get.rs, cmd/src/cmd/topic/list.rs, cmd/src/cmd/topic/update.rs, cmd/src/main.rs, iggy/src/identifier.rs
Add to each command long help with additional information and section with examples of command usage. Remove debug print for topic get command.
=> Extend help for each command with examples

Cargo.lock, iggy/Cargo.toml, server/Cargo.toml
This commit fix #2 security alert related to aes-gcm crate and CVE-2023-42811
=> Update aes-gcm to 0.10.3 in order to fix CVE-2023-42811

Cargo.lock, cmd/Cargo.toml, cmd/src/args/mod.rs, cmd/src/args/partition.rs, cmd/src/cmd/mod.rs, cmd/src/cmd/partition/create.rs, cmd/src/cmd/partition/delete.rs, cmd/src/cmd/partition/mod.rs, cmd/src/main.rs
Adding set of modules under cmd::partition module which implement partition specific commands. Adding also args::partition modules which contain command line args parser definitions and help messages.
Updating iggy tool to 0.3.0
=> Add partition related commands

Cargo.lock, cmd/Cargo.toml, cmd/src/args/mod.rs, cmd/src/error.rs, cmd/src/login.rs, cmd/src/main.rs
Since Iggy server requires authentication adding username and password which allows users to provide credentials to log into iggy server. If password is not provided in command line arguments iggy tool asks for password.
=> Add username and password command line options

Cargo.lock, server/Cargo.toml, server/src/streaming/cache/buffer.rs, server/src/streaming/partitions/messages.rs
pop_front() was used instead of pop_back(), which
resulted in invalid offset calculation.
=> Fix message cache

cmd/Cargo.toml, iggy/Cargo.toml, iggy/src/args.rs
Features control presence of username and password members in Args struct used for iggy SDK parameters parsing. Both features are enabled by default in iggy crate. Both are disabled in iggy-cmd crate in order to be able to introduce different handling of both parameters in iggy command line tool.
=> Add two default features to iggy username-in-args and password-in-args

iggy/src/models/identity_info.rs, iggy/src/models/user_info.rs, server/src/binary/mapper.rs, server/src/http/jwt.rs, server/src/streaming/cache/memory_tracker.rs, server/src/streaming/clients/client_manager.rs, server/src/streaming/session.rs, server/src/streaming/users/permissioner.rs, server/src/streaming/users/storage.rs, server/src/streaming/users/user.rs
Applied two type aliases for 
- `user_id`
- `message_size`
Reasoning for using alias (`type X = u32`) over newtype (`struct X(u32)`)
- Client facing types get cluttered by newtype, requires recreating type which can unneccessarily clutter the SDK:
```rust
let user = UserInfoDetails {
id: 1,
...
};
```
becomes
```rust
let user = UserInfoDetails {
id: UserId(1),
...
};
```
which may be more confusing, likewise similar issue on getting an attribute's value
type alias 
```rust
user.id
```
newtype
```rust
user.id.0
```
which imo is not as nice and makes the SDK harder to use.
Therefore on client facing types I think its best to use type aliases.
newstruct types also lose the traits of the internal type, requiring which requires a larger refactor/custom implementations for non-derivable …
=> chore: own-defined types for various simple types

Cargo.lock, cmd/Cargo.toml, cmd/src/credentials.rs, cmd/src/main.rs, iggy/src/cli_command.rs, iggy/src/cmd/system/ping.rs
Ping command usage is allowed without login to iggy server. Extending CliCommand trait with additional method which controls whether command needs server login and making adaptations in IggyCredentials to support object creation with and without mandatory login.
=> Fix problem with mandatory login for ping command

Cargo.lock, cmd/Cargo.toml, cmd/tests/common/command.rs, cmd/tests/common/mod.rs, cmd/tests/common/server.rs, cmd/tests/common/tcp.rs, cmd/tests/general/mod.rs, cmd/tests/general/test_missing_credentials.rs, cmd/tests/general/test_quiet_mode.rs, cmd/tests/mod.rs, cmd/tests/system/mod.rs, cmd/tests/system/test_me_command.rs, cmd/tests/system/test_ping_command.rs, cmd/tests/system/test_stats_command.rs, tools/Cargo.toml
Add framework for building tests for iggy-cmd using same logic as in tests for iggy-server where server instance is started with supporting iggy tcp client for test setup and teardown. Adding trait for single test case implementation and logic to execute such tests. Add some basic tests for
- general functionality - quiet mode, missing credentials
- system commands - me, ping, stats
=> Add integration tests to iggy-cmd

cmd/tests/common/server.rs
mut is not needed by Linux but due to usage of child_handle.kill() only for Windows handle must stay mutable.
=> Keep mut child handle in iggy-cmd tests

cmd/tests/common/command.rs, cmd/tests/common/mod.rs, cmd/tests/common/server.rs, cmd/tests/general/test_missing_credentials.rs, cmd/tests/general/test_quiet_mode.rs, cmd/tests/mod.rs, cmd/tests/stream/mod.rs, cmd/tests/stream/test_stream_create_command.rs, cmd/tests/stream/test_stream_delete_command.rs, cmd/tests/stream/test_stream_get_command.rs, cmd/tests/stream/test_stream_list_command.rs, cmd/tests/stream/test_stream_update_command.rs, cmd/tests/system/test_me_command.rs, cmd/tests/system/test_ping_command.rs, cmd/tests/system/test_stats_command.rs, iggy/src/cmd/streams/update_stream.rs, server/tests/server_tests/common/mod.rs
Add integration tests for stream commands. This partially implements #146.
Rename existing test names to more meaningful. Add check in test framework
if iggy server is running.
=> Add integration tests for stream commands

integration/tests/cmd/general/mod.rs, integration/tests/cmd/general/test_help_command.rs, integration/tests/cmd/stream/mod.rs, integration/tests/cmd/stream/test_stream_create_command.rs, integration/tests/cmd/stream/test_stream_delete_command.rs, integration/tests/cmd/stream/test_stream_get_command.rs, integration/tests/cmd/stream/test_stream_help_command.rs, integration/tests/cmd/stream/test_stream_list_command.rs, integration/tests/cmd/stream/test_stream_update_command.rs, integration/tests/cmd/system/test_me_command.rs, integration/tests/cmd/system/test_ping_command.rs, integration/tests/cmd/system/test_stats_command.rs, integration/tests/cmd/topic/test_topic_create_command.rs, integration/tests/cmd/topic/test_topic_delete_command.rs, integration/tests/cmd/topic/test_topic_get_command.rs, integration/tests/cmd/topic/test_topic_list_command.rs, integration/tests/cmd/topic/test_topic_update_command.rs
Add integration tests for help messages for other iggy commands #146
Add integration tests for checking help message output for general, system and stream related commands in iggy-cmd. Replace serial with parallel in all iggy cmd integration tests.
This fixes #146. Implementation of missing SDK commands in iggy cmd will cover also testing.
=> Add integration tests for help messages for other iggy commands #146

Cargo.lock, cmd/Cargo.toml, cmd/src/args/common.rs, cmd/src/args/mod.rs, cmd/src/args/personal_access_token.rs, cmd/src/main.rs, iggy/Cargo.toml, iggy/src/cmd/mod.rs, iggy/src/cmd/personal_access_tokens/create_personal_access_token.rs, iggy/src/cmd/personal_access_tokens/delete_personal_access_tokens.rs, iggy/src/cmd/personal_access_tokens/get_personal_access_tokens.rs, iggy/src/cmd/personal_access_tokens/mod.rs, iggy/src/cmd/utils/mod.rs, iggy/src/cmd/utils/personal_access_token_expiry.rs, iggy/src/utils/timestamp.rs, integration/tests/cmd/general/test_help_command.rs, integration/tests/cmd/mod.rs, integration/tests/cmd/personal_access_token/mod.rs, integration/tests/cmd/personal_access_token/test_pat_create_command.rs, integration/tests/cmd/personal_access_token/test_pat_delete_command.rs, integration/tests/cmd/personal_access_token/test_pat_help_command.rs, integration/tests/cmd/personal_access_token/test_pat_list_command.rs
Add pat command with create, delete and list subcommands to iggy-cmd. Extend integration tests with cases which cover all new commands. This commit partially implements #182
=> Add support for personal access tokens to iggy-cmd

Cargo.lock, cmd/Cargo.toml, cmd/src/args/mod.rs, cmd/src/args/personal_access_token.rs, cmd/src/credentials.rs, cmd/src/error.rs, cmd/src/main.rs, iggy/Cargo.toml, iggy/src/cmd/personal_access_tokens/create_personal_access_token.rs, iggy/src/cmd/personal_access_tokens/delete_personal_access_tokens.rs, integration/tests/cmd/general/test_help_command.rs, integration/tests/cmd/personal_access_token/test_pat_create_command.rs
Add new command line options which allow user to use personal access token and personal access token name to authorize on iggy server. Adding option to pat create command which stores token value in platform-specific secure store for usage with token name authorization. Token is stored under iggy server IP address (with "iggy:" prefix) and token name given during token name creation. Only personal access tokens without expiry time are stored in platform specific storage.
=> Add support for personal access token authorization in iggy cmd tool

Cargo.lock, server/Cargo.toml, server/src/binary/mapper.rs
Replaced put_u64 with put_u64_le in order to serialize data in little-endian byte order.
=> Fix serialization of created_at for User objects

Cargo.lock, cmd/Cargo.toml, cmd/src/args/mod.rs, cmd/src/args/partition.rs, cmd/src/args/personal_access_token.rs, cmd/src/args/stream.rs, cmd/src/args/system.rs, cmd/src/args/topic.rs, cmd/src/args/user.rs, cmd/src/main.rs, integration/tests/cmd/general/mod.rs, integration/tests/cmd/general/test_help_command.rs, integration/tests/cmd/general/test_overview_command.rs
Set command as optional and handle missing command as proper action and print reduced help message with commands overview and general info about iggy.
=> Add overview to iggy-cmd by setting command as optional

Cargo.lock, cmd/Cargo.toml, cmd/src/args/mod.rs, cmd/src/main.rs, integration/tests/cmd/general/test_help_command.rs
Add an option which allows to generate shell completion code for selected shell.
=> Add shell completion generator to iggy-cmd options

Cargo.lock, iggy/Cargo.toml, iggy/src/utils/duration.rs
Replace usage of human-time with format_duration from humantime crate
=> Remove usage of human-time crate

.github/workflows/test_nightly.yml
No sense in running it, since it's required to every
PR. This fixes #306.
=> Don't run sanity on test_nightly

Cargo.lock, cmd/Cargo.toml, cmd/src/args/mod.rs, cmd/src/args/user.rs, cmd/src/main.rs, iggy/Cargo.toml, iggy/src/cli_command.rs, iggy/src/cmd/users/change_password.rs, iggy/src/cmd/users/mod.rs, iggy/src/cmd/users/update_user.rs, integration/tests/cmd/general/test_help_command.rs, integration/tests/cmd/user/mod.rs, integration/tests/cmd/user/test_user_create_command.rs, integration/tests/cmd/user/test_user_help_command.rs, integration/tests/cmd/user/test_user_name_command.rs, integration/tests/cmd/user/test_user_password_command.rs, integration/tests/cmd/user/test_user_status_command.rs
Adding user name, status and password commands for changing given user
login / username, status (active / inactive) and password using iggy
command line tool. Adding integration tests for those commands.
Extend CliCommand trait with new method which allows particular commands
to use direct standard output for printing messages instead of tracing
events. Using new method for user password command which interactively
asks user in a secure way for current and new password.
=> Add new user commands to iggy cmd

Cargo.lock, cmd/Cargo.toml, cmd/src/args/user.rs, cmd/src/main.rs, iggy/Cargo.toml, iggy/src/cmd/users/mod.rs, iggy/src/cmd/users/update_permissions.rs, integration/tests/cmd/user/common.rs, integration/tests/cmd/user/mod.rs, integration/tests/cmd/user/test_user_delete_command.rs, integration/tests/cmd/user/test_user_get_command.rs, integration/tests/cmd/user/test_user_help_command.rs, integration/tests/cmd/user/test_user_name_command.rs, integration/tests/cmd/user/test_user_password_command.rs, integration/tests/cmd/user/test_user_permissions_command.rs, integration/tests/cmd/user/test_user_status_command.rs
Add command user permissions which allows to set permissions for given
user. Command has same set of permissions related parameters as user
create command. Add integration test for checking user permissions
command. Improved help message for user commands where user ID is used.
=> Add user permissions command to iggy cmd

Cargo.lock, server/Cargo.toml
Upon merge of this commit, new tag shall be created, eg. iggy-0.0.123 and SDK 'iggy' shall be updated to 0.0.123 on crates.io.
=> Test automatic release of iggy-server to dockerhub

integration/tests/cmd/common/mod.rs, integration/tests/cmd/user/test_login_options.rs, integration/tests/cmd/user/test_user_password_command.rs
Extend test case trait with method which allows test to send strings to
iggy cmd stdin. By default method returns None. Extending tests for
server authentication and user password command with new mechanism
in order to provide passwords from standard input of iggy command.
=> Add mechanism to test iggy cmd by providing data to stdin

Cargo.lock, server/Cargo.toml, server/src/logging/mod.rs
It turns out that both file layer and stdout layer need
it's own filters. Besides that, tracing-subscriber
is updated to 0.3.18.
=> Fix logging when log level is selected from config

.github/workflows/test_nightly.yml, integration/tests/cmd/general/test_missing_credentials.rs
Change how test_missing_credentials test validates correctness of iggy cmd output. Add gnome-keyring keyutils to list of installed SW for CI machines in nightly run.
This fix #354
=> Change test condition and add missing SW for CI

.github/workflows/release.yml
=> Add missing condition to creat gh release only if tag was created

.github/workflows/release.yml
Due to restriction in upload-artifact@v4+ there's no possibility
to use the same name for several artifacts uploaded to the registry.
Setting suffix for digest artifact and download it during merge
using pattern.
This fix #399 #400 #401 #402 #403 #404
=> Add suffix to artifact name for digest upload and download

.github/workflows/release.yml
With this setting all digest artifacts will be placed in /tmp/digests
instead of subfolders.
This fix #406
=> Download artifacts to the same directory

Cargo.lock, cmd/Cargo.toml, cmd/src/args/client.rs, cmd/src/args/common.rs, cmd/src/args/mod.rs, cmd/src/main.rs, iggy/Cargo.toml, iggy/src/cmd/client/get_client.rs, iggy/src/cmd/client/get_clients.rs, iggy/src/cmd/client/mod.rs, iggy/src/cmd/mod.rs, integration/tests/cmd/client/mod.rs, integration/tests/cmd/client/test_client_get_command.rs, integration/tests/cmd/client/test_client_help_command.rs, integration/tests/cmd/client/test_client_list_command.rs, integration/tests/cmd/general/test_help_command.rs, integration/tests/cmd/general/test_overview_command.rs, integration/tests/cmd/mod.rs
Add two new commands to iggy command line client (cmd) for listing
clients connected to iggy server (client list) and getting detailed
information about particular client (client get).
=> Add client get and client list commands with integration tests

.github/dependabot.yml, README.md
Remove crates from dependabot.yml to let it use Cargo workspace settings
and check and update all creates instead of tpc only. Add dependencies
badge for which shows actual status of known security vulnerabilities.
Change dependabot schedule to daily for Rust crates checks.
=> Fix dependabot configuration and add dependencies badge

server/src/main.rs
Removed the unused statements to resolve the build warnings in server.
Closes #492.
=> Resolve build warnings in `iggy-server` for Windows build

.github/workflows/test_nightly.yml, integration/tests/examples/mod.rs
This fixes #507.
This PR updates the examples integration tests to handle the QEMU_RUNNER env variable used in the test_nightly GH action workflow
=> Fix test_nightly test suite problem with starting examples binary

Cargo.lock, server/Cargo.toml, server/src/streaming/partitions/consumer_offsets.rs, server/src/streaming/partitions/messages.rs, server/src/streaming/partitions/partition.rs
Resolve https://github.com/iggy-rs/iggy/issues/226
I used the `DashMap` to replace the original `RwLock<HashMap>`, and because the locking of `DashMap` is synchronous semantics, I had to use clone in the `fn store_offset` to avoid the lock crossing await.
=> Add dashmap crate for concurrent hashmap operations

integration/tests/streaming/segment.rs, server/src/channels/commands/save_messages.rs, server/src/main.rs, server/src/streaming/partitions/messages.rs, server/src/streaming/segments/messages.rs, server/src/streaming/streams/persistence.rs, server/src/streaming/systems/system.rs, server/src/streaming/topics/persistence.rs
The parameter in `persist_messages` method, which seemed redundant, so I removed it.
=> Remove useless params in persist_messages

.github/CODEOWNERS
So that workflow approval is required when this
directory is changed by person that isn't maintainer.
=> Assign CODEOWNERS for .github directory

iggy/src/messages/mod.rs, server/src/binary/command.rs, server/src/quic/listener.rs
I found that some of the code in `QUIC server` was not rusty enough, so I refactored it to make it more readable.
I'm using anyhow in some places for now, it's not the final solution. But if a more standard error handling is needed it may require a refactoring of the current Errors, maybe we can improve it later.😊
=> Refactor QUIC stream handling

examples/src/getting-started/consumer/main.rs, examples/src/getting-started/producer/main.rs, integration/src/test_server.rs, integration/tests/examples/mod.rs, integration/tests/examples/test_basic.rs, integration/tests/examples/test_getting_started.rs, integration/tests/examples/test_message_envelope.rs, integration/tests/examples/test_message_headers.rs
There was problem on MacOS in which examples output was collected too quickly. This commit changes behavior of testcase so that is checks the output of consumer/producer after the executable is finished.
Besides that, this commit refactors the TCP client creation process in the getting-started examples for both consumer and producer. It introduces the ability to specify the server address via command-line arguments.
Additionally, it adjusts the BATCHES_LIMIT constant and adds a new function to retrieve the TCP server address. The integration tests have been updated to reflect these changes, and the MAX_PORT_WAIT_ DURATION_S constant has been conditionally set based on the build environment.
Besides that, now all tests (-1) are working in parallel 🦀
=> Fix testing examples on MacOS

iggy/src/models/user_info.rs, server/src/binary/command.rs, server/src/binary/handlers/personal_access_tokens/create_personal_access_token_handler.rs, server/src/binary/handlers/personal_access_tokens/delete_personal_access_token_handler.rs, server/src/binary/handlers/personal_access_tokens/login_with_personal_access_token_handler.rs, server/src/binary/handlers/users/change_password_handler.rs, server/src/binary/handlers/users/create_user_handler.rs, server/src/binary/handlers/users/delete_user_handler.rs, server/src/binary/handlers/users/login_user_handler.rs, server/src/binary/handlers/users/logout_user_handler.rs, server/src/binary/handlers/users/update_permissions_handler.rs, server/src/binary/handlers/users/update_user_handler.rs, server/src/quic/listener.rs, server/src/streaming/session.rs, server/src/streaming/systems/clients.rs, server/src/streaming/systems/consumer_groups.rs, server/src/streaming/systems/consumer_offsets.rs, server/src/streaming/systems/messages.rs, server/src/streaming/systems/partitions.rs, server/src/streaming/systems/personal_access_tokens.rs, server/src/streaming/systems/stats.rs, server/src/streaming/systems/streams.rs, server/src/streaming/systems/topics.rs, server/src/streaming/systems/users.rs, server/src/tcp/connection_handler.rs
Currently, the quic server handles `streams` serially per `connection`. It seems that a change to parallel processing of `streams` is necessary, as clients can afford to send streams concurrently using a single `quic connection`.
=> Supports concurrent handling of quic streams

integration/src/test_server.rs
This PR is to fix #479. It adds a simple check to see if the server process has exited and panic in this case.
While doing integration tests, a separated server process is started, and the test case would wait for the server process to starting a loop to check if the `local_data_xxx/runtime/current_config.toml` file is created. If the file is not created, it would sleep and check again. If the server process exited, the waiting would take a long time until the loop reaches the max attempts. By checking the process status, we can fail the test sooner.
=> Check if the process has existed while waiting for test server to start

Cargo.lock, cli/Cargo.toml, cli/src/args/stream.rs, cli/src/args/topic.rs, cli/src/main.rs, integration/tests/cli/stream/mod.rs, integration/tests/cli/stream/test_stream_help_command.rs, integration/tests/cli/stream/test_stream_purge_command.rs, integration/tests/cli/topic/mod.rs, integration/tests/cli/topic/test_topic_help_command.rs, integration/tests/cli/topic/test_topic_purge_command.rs, sdk/Cargo.toml, sdk/src/cli/streams/mod.rs, sdk/src/cli/streams/purge_stream.rs, sdk/src/cli/topics/mod.rs, sdk/src/cli/topics/purge_topic.rs
Add purge sub-command for stream and topic commands which allow
user to remove all messages from specific topic or stream.
Add integration tests for the new purge commands.
Close #579
=> Add purge sub-command for stream and topic commands

.github/workflows/post_release.yml
Closes #361
Sample post_release workflow run: https://github.com/iggy-rs/iggy/actions/runs/7613469410/job/20733424469?pr=581
Discord chat: https://discord.com/channels/1144142576266530928/1144144507315691521/1196486487143878727
**Notes / Assumptions:** 
**1. Choice of Docker Image Tagging:**
- Our current `release.yml` workflow automatically tags images pushed to Dockerhub with `latest`. If a new version tag exists, the image will also be tagged with that specific version number. 
- In `post_release.yml`, I have opted to only use `iggrs/iggy:latest`, excluding specific version tags. To fetch version tags, we would need to integrate the `post_release` job into `release.yml`, which would lengthen the release process.
**2. Execution Environment for the Workflow:**
- In `post_release.yml`, I …
=> Test latest docker image in CI after it's release to dockerhub

.github/workflows/publish_sdk.yml
Change the version extraction command in the publish_sdk.yml
workflow to use '@' as the delimiter instead of '#'. This ensures
correct version parsing for the iggy package.
=> Update version extraction method in publish_sdk workflow

Cargo.lock, cli/Cargo.toml, cli/src/args/stream.rs, cli/src/args/topic.rs, integration/tests/cli/stream/test_stream_create_command.rs, integration/tests/cli/stream/test_stream_help_command.rs, integration/tests/cli/topic/test_topic_create_command.rs, integration/tests/cli/topic/test_topic_help_command.rs, sdk/src/cli/streams/create_stream.rs, sdk/src/cli/topics/create_topic.rs
Modify the stream and topic creation commands to allow the server to
automatically assign IDs if they are not provided by the user. Update
help messages, tests, and internal command structures to reflect the
new optional ID behavior.
Close #579
=> Refactor stream and topic creation to support auto ID assignment

integration/tests/examples/test_getting_started.rs, sdk/src/error.rs, sdk/src/tcp/client.rs
To summarize what was discussed on discord:
Attempting to create topics and streams that have already been created currently logs at the error level. For example:
```
2024-01-25T15:27:32Z ERROR  Received an invalid response with status: 1012 (stream_name_already_exists).
```
This may happen as a result of users simply to always create a topic upon producer/consumer initialization, as a means to avoid topic/stream not found error handling.  One fix would be to require users to check topic existences first, but this would often result in two request being done rather than just one.
Users already need to explicitly ignore this "error" in the SDK, so I think it's ok to simply increase the corresponding log levels to debug. It also makes things easier for users that don't want to filter away …
=> Log stream/topic already exists as debug events.

Cargo.lock, cli/Cargo.toml, cli/src/args/consumer_offset.rs, cli/src/args/mod.rs, cli/src/main.rs, integration/tests/cli/common/mod.rs, integration/tests/cli/consumer_offset/mod.rs, integration/tests/cli/consumer_offset/test_consumer_offset_get_command.rs, integration/tests/cli/consumer_offset/test_consumer_offset_set_command.rs, integration/tests/cli/general/test_help_command.rs, integration/tests/cli/general/test_overview_command.rs, integration/tests/cli/mod.rs, sdk/Cargo.toml, sdk/src/cli/consumer_offset/get_consumer_offset.rs, sdk/src/cli/consumer_offset/mod.rs, sdk/src/cli/consumer_offset/set_consumer_offset.rs, sdk/src/cli/mod.rs
This commit introduces new CLI commands for managing consumer offsets.
The `consumer-offset get` command retrieves the offset of a consumer for
a given partition from the server, while the `consumer-offset set`
command allows setting the offset of a consumer for a given partition on
the server. The changes include updates to the CLI interface, integration
tests, and the SDK to support these new functionalities.
Close #545
=> Add consumer offset management commands

.github/workflows/sanity.yml
We switched some jobs to `push`, so github automatically adds #XYZ hashtag at the end.
=> Allow hashtags in the commit title

.config/nextest.toml, Cargo.lock, cli/Cargo.toml, cli/src/args/mod.rs, cli/src/args/system.rs, cli/src/credentials.rs, cli/src/main.rs, integration/src/test_server.rs, integration/tests/cli/common/mod.rs, integration/tests/cli/general/test_help_command.rs, integration/tests/cli/general/test_overview_command.rs, integration/tests/cli/system/mod.rs, integration/tests/cli/system/test_cli_session_scenario.rs, integration/tests/cli/system/test_login_cmd.rs, integration/tests/cli/system/test_login_command.rs, integration/tests/cli/system/test_logout_cmd.rs, integration/tests/cli/system/test_logout_command.rs, integration/tests/cli/system/test_me_command.rs, integration/tests/cli/system/test_stats_command.rs, sdk/Cargo.toml, sdk/src/cli/system/login.rs, sdk/src/cli/system/logout.rs, sdk/src/cli/system/mod.rs, sdk/src/cli/system/session.rs, sdk/src/cli/utils/login_session_expiry.rs, sdk/src/cli/utils/mod.rs
This commit introduces the ability to handle authenticated session
for Iggy CLI. Two new commands, Login and Logout, have been added
to the command list. The IggyCredentials struct has been updated
to support token retrieval from a ServerSession. Login command
use system's keyring service to store PAT which is created after
successful authentication during Login command. Logout command
removes dedicated PAT and cleans keyring data. In case of PAT
removal on Iggy Server Iggy CLI does cleanup in system's keyring
service and informs user that server session has been terminated.
Adding integration tests which verify Iggy CLI Login and Logout.
Updating Ping, Me and Stats help messages and corresponding tests.
Adding nextest config with requirement that login/logout test
scenario must run …
=> Add login and logout commands to Iggy CLI

Cargo.lock, cli/src/credentials.rs, sdk/Cargo.toml, sdk/src/error.rs, sdk/src/quic/client.rs, sdk/src/tcp/client.rs, server/Cargo.toml, server/src/quic/quic_sender.rs, server/src/tcp/sender.rs
This commit enhances InvalidResponse error enum by adding detailed error
string and its length in order to be able to send it over the wire.
Corresponding changes have been made in the QUIC and TCP client to
rebuild detailed error responses on client side. This will improve
debugging and user feedback when errors occur.
This fixes #686
=> Update error handling to include detailed messages

justfile, scripts/profile.sh
This commit introduces the ability to perform I/O profiling for both the
server (`iggy-server`) and the client (`iggy-bench`). The `profile.sh`
script has been updated to accept a second argument specifying the
profiling mode, which can be either 'cpu' or 'io'.
The justfile aliases `ps` and `pc` have been renamed to `pcs` and `pcc`
to reflect CPU profiling, and new aliases `pis` and `pic` have been
added for I/O profiling.
Additionally, the commit ensures that the FlameGraph repository is
cloned to `/tmp` if it's not already present when I/O profiling is
selected. The script also checks for the correct system settings for
perf and provides instructions to the user if adjustments are needed.
Flamegraph SVG filenames now include the profiling mode to distinguish
between CPU and I/O …
=> Add I/O profiling support to profiling scripts

README.md
The README has been updated to correct the command used to execute the
CLI within the running Docker container. The path to the CLI has been
changed from '/cli' to '/iggy/iggy' to reflect the current structure.
This fix #697
=> Update CLI execution path in README

bench/src/benchmarks/benchmark.rs, bench/src/consumer.rs, bench/src/producer.rs, cli/src/main.rs, examples/src/getting-started/consumer/main.rs, examples/src/getting-started/producer/main.rs, examples/src/message-envelope/consumer/main.rs, examples/src/message-envelope/producer/main.rs, examples/src/message-headers/consumer/main.rs, examples/src/message-headers/producer/main.rs, integration/tests/cli/common/mod.rs, integration/tests/examples/mod.rs, integration/tests/server/scenarios/consumer_group_join_scenario.rs, integration/tests/server/scenarios/consumer_group_with_multiple_clients_polling_messages_scenario.rs, integration/tests/server/scenarios/consumer_group_with_single_client_polling_messages_scenario.rs, integration/tests/server/scenarios/message_headers_scenario.rs, integration/tests/server/scenarios/stream_size_validation_scenario.rs, integration/tests/server/scenarios/system_scenario.rs, integration/tests/server/scenarios/user_scenario.rs, sdk/src/client_provider.rs, sdk/src/clients/builder.rs, sdk/src/clients/client.rs, sdk/src/clients/mod.rs, sdk/src/http/config.rs, sdk/src/quic/config.rs, sdk/src/tcp/config.rs, tools/src/data-seeder/main.rs
This is related to https://github.com/iggy-rs/iggy/issues/528.
I could not find a way to make config a trait in a nice way. So I was deciding with either single `with_config` where the configs be wrapped in an enum, or multiple with methods. The latter seemed more natural to me.
This is a way to construct a client with tcp now:
```
let tcp_client_config = TcpClientConfig {
server_address: get_tcp_server_addr(),
..TcpClientConfig::default()
};
let client = IggyClientBuilder::new()
.with_tcp_config(tcp_client_config)
.build()?;
```
To consider:
- should  `TCP, QUICK, HTTP` client configs be abstracted as well (or at least re export them), so the users don't have to include `iggy::tcp::config` for example?
=> Improve IggyClientBuilder: speficic underlying client creation

Cargo.lock, server/Cargo.toml, server/src/streaming/systems/streams.rs, server/src/streaming/systems/users.rs, server/src/streaming/users/user.rs
From now on, you can provide the `IGGY_ROOT_USERNAME` and `IGGY_ROOT_PASSWORD` environment variables in order to create the root user using your own credentials, instead of the default ones.
=> Allow root user credentials configuration

Cargo.lock, cli/Cargo.toml, integration/tests/cli/common/command.rs, integration/tests/cli/system/test_cli_session_scenario.rs, integration/tests/cli/system/test_login_cmd.rs, integration/tests/cli/system/test_logout_cmd.rs, integration/tests/cli/system/test_me_command.rs, sdk/src/cli/system/login.rs
This commit overhauls the integration tests for the CLI's login and me
commands to handle multiple scenarios, including successful logins,
logins with timeouts, and session expiration. The TestLoginCmd now
supports different types of login attempts, such as logging in with an
already active session or with a token already present. The TestMeCmd
has been extended to test the behavior of the me command under various
conditions, like without credentials or after a session timeout. The
login command in the SDK has been updated to delete and recreate the
login session if the local keyring is empty but a token exists on the
server, ensuring that the token on the server and the local keyring are
in sync.Disable Rust backtrace for selected iggy cli command calls
during tests.
=> Refactor login and me command tests for various scenarios

Cargo.lock, sdk/Cargo.toml, sdk/src/utils/timestamp.rs, server/Cargo.toml
- Refactor IggyTimestamp to manually implement Serialize and Deserialize
because #696 broke backwards compatibility due to bug in which SystemTime was stored instead of epoch u64 micros
- Bump iggy version from 0.2.5 to 0.2.6
- Bump server version from 0.2.3 to 0.2.4
=> Fix `IggyTimestamp` serialization

.github/workflows/release.yml, .github/workflows/test_nightly.yml, Cross.toml, integration/src/test_server.rs, integration/tests/bench/mod.rs, integration/tests/cli/common/mod.rs, integration/tests/examples/mod.rs
This commit removes the conditional QEMU runner blocks that were previously required to start binaries via QEMU when running actions from GitHub CI for ARM architectures. The removal affects several integration test files where the QEMU runner logic is no longer necessary since new version of assert_cmd crate directly support correct commands execution under cross tool.
This fix #705 #709 #713 #716 #718 #720 #722
=> Remove QEMU runner blocks for GitHub CI

bench/src/args/common.rs, bench/src/benchmark_result.rs, bench/src/benchmarks/poll_benchmark.rs, bench/src/benchmarks/send_and_poll_benchmark.rs, bench/src/benchmarks/send_benchmark.rs, bench/src/consumer.rs, bench/src/main.rs, bench/src/producer.rs, integration/tests/bench/mod.rs
This commit introduces a warmup time parameter to the benchmarking suite,
allowing for a configurable duration of warmup before measurements begin.
The warmup phase helps to stabilize the system, leading
to more consistent and accurate benchmark results. The `IggyDuration`
is utilized to manage the warmup duration, ensuring precise control over
the warmup period. Additionally, this update includes a fix for a typo in
the `calculate_statistics` method name.
=> Add warmup phase to benchmarks with configurable duration

.github/workflows/post_release.yml, bench/src/args/common.rs, bench/src/args/defaults.rs, bench/src/server_starter.rs
Ensure iggy-server is ready by waiting for TCP port 8090 to bind before
benchmarks. Update Docker image to use the latest tag. Introduce a
check for the correct message count after benchmarks. Refactor
benchmark arguments to include defaults for warmup time and server
start skipping. Adjust server starter logic to respect the new
skip server start option.
=> Fix post_release flow

.github/workflows/test_nightly.yml, .gitignore, Cross.toml, Dockerfile.cross, integration/tests/cli/personal_access_token/mod.rs, integration/tests/cli/system/mod.rs, scripts/cross-docker-entrypoint.sh, scripts/prepare-cross-toml.sh
This commit introduces several changes to improve the cross-compilation
testing environment by adding Docker support for keyring functionality.
Add CROSS_CONTAINER_OPTS to GitHub workflows to enable IPC lock
capabilities, allowing keyring usage within Docker containers.
Create a new Dockerfile.cross to set up a Docker image with gnome-keyring
installed and configured a user with the appropriate UID and GID. Add
a new entrypoint script cross-docker-entrypoint.sh for the Docker
container to handle keyring unlocking and execution of the test commands.
Generate a Cross.toml configuration file using prepare-cross-toml.sh
script to pass the current user's UID and GID to the Docker build context.
Adjusted integration tests to reflect the new keyring support in Docker
for ARM and AArch64 …
=> Add Docker support for keyring in cross-compilation tests

.github/workflows/post_release.yml
This commit introduces a network check to confirm that port 8090
is open before proceeding with the post-release actions.
Additionally, a one-second pause has been added to ensure that
any transient conditions have time to stabilize. This should
help in troubleshooting and ensuring that the iggy server is
ready for the subsequent test benchmark step.
This fixes #787, fixes #792, fixes #793, fixes #795, fixes #801,
fixes #802, fixes #804, fixes #810
=> Add network check and pause in post-release workflow

Cargo.lock, configs/server.toml, server/Cargo.toml, server/src/configs/defaults.rs, server/src/configs/http.rs, server/src/configs/system.rs, server/src/configs/tcp.rs, server/src/http/http_server.rs
This commit streamlines the server configuration by utilizing the static
SERVER_CONFIG for setting default values. It removes hardcoded strings and
replaces them with parsed values from the configuration file, ensuring
consistency and maintainability. The changes include updates to CORS headers,
QUIC, HTTP, and other server components, enhancing the configuration's
flexibility and readability.
=> Refactor server configuration defaults to use static config

Cargo.lock, integration/tests/server/scenarios/message_size_scenario.rs, integration/tests/server/scenarios/mod.rs, integration/tests/server/tcp_server.rs, sdk/Cargo.toml, sdk/src/clients/client.rs, sdk/src/error.rs, server/src/tcp/connection_handler.rs
This commit introduces a new test scenario for TCP server to validate
existing message size constraints (for payload and headers).
Updating implementation of IggyClient in the SDK to return an error
when attempting to send an empty message array. Handling of command
length errors in the TCP connection handler to provide more
informative error messages and continue processing subsequent
commands instead of closing connection (which ends on client side
with cryptic eof message).
This is pre-work for #21
=> Add message size validation scenario for TCP server

sdk/src/error.rs, server/src/tcp/connection_handler.rs, server/src/tcp/sender.rs
This commit introduces improved error handling for the case when a TCP
connection is closed by the client. The SDK now includes a specific
error for this scenario, and the server's connection handler has been
updated to return an error when the connection is closed, rather than
continuing to attempt to read from the stream. Additionally, the error
handling logic distinguishes between a closed connection and other SDK
errors, logging a debug message for the former and an error for the
latter. The read function in the sender module has also been modified
to return a ConnectionClosed error when an EOF is encountered.
=> Improve connection handling and closure in TCP server

Cargo.lock, sdk/Cargo.toml, sdk/src/client.rs, sdk/src/clients/client.rs, sdk/src/clients/next_client.rs, sdk/src/next_client.rs
Instead of the existing `Client` and `IggyClient` the `ClientNext` and `IggyClientNext` components should be used.
=> Prepare existing Client and IggyClient for the future migration

cli/src/args/message.rs, cli/src/main.rs, integration/tests/cli/message/test_message_poll_command.rs, integration/tests/cli/message/test_message_send_command.rs, sdk/src/cli/message/poll_messages.rs, sdk/src/cli/message/send_messages.rs, sdk/src/error.rs, sdk/src/models/header.rs
This refers to #646
- You can set headers in message send command with a comma separated list and the format key:kind:value
- Sends messages with the provided header
- Option to display the headers with the poll command
If you want to have already a look on it. Please. I'm not happy with the `value_only_to_string` function in the HeaderValue impl. I tried a struct for `value` and implement `Display` for it. But obviously we don't have the `HeaderKind` then. And `Display` for `HeaderKind` is already implemented in a different way.
=> Add support for message headers to send and poll commands

Cargo.lock, server/Cargo.toml, server/src/channels/commands/clean_messages.rs
This commit resolves a deadlock by acquiring a write lock on the system
once instead of multiple times within the CleanMessagesExecutor. The
redundant system.write() calls have been removed, ensuring that the
metrics are updated without the need for additional locks.
This closes #897.
=> Fix deadlock issue in CleanMessagesExecutor

cli/src/args/topic.rs, integration/tests/cli/topic/test_topic_create_command.rs, integration/tests/cli/topic/test_topic_help_command.rs, integration/tests/cli/topic/test_topic_update_command.rs
Updated topic create and topic update cli help messages to include
compression algorithm information and updated examples.
Adjusted integration tests to match the updated command syntax.
=> Add compression info to help for topic cli commands

.github/workflows/sanity.yml, Cargo.lock, Cargo.toml, bench/Cargo.toml, cli/Cargo.toml, examples/Cargo.toml, integration/Cargo.toml, server/Cargo.toml, tools/Cargo.toml, tpc/Cargo.toml
Remove unused dependencies using machete from whole iggy workspace.
Add configuration for machete to workspace Cargo.toml in order to
keep openssl crate (due to failing musl builds when it is removed).
=> Enable unused dependencies check using cargo machete

cli/src/args/partition.rs, cli/src/args/personal_access_token.rs, cli/src/args/topic.rs, cli/src/args/user.rs, sdk/src/binary/consumer_groups.rs, sdk/src/cli/consumer_group/create_consumer_group.rs, sdk/src/client.rs, sdk/src/clients/client.rs, sdk/src/http/consumer_groups.rs, sdk/src/utils/expiry.rs, server/server.http, server/src/binary/handlers/consumer_groups/create_consumer_group_handler.rs, server/src/compat/snapshots/message_snapshot.rs, server/src/http/consumer_groups.rs, server/src/streaming/systems/consumer_groups.rs, server/src/streaming/topics/consumer_groups.rs
Creating a consumer group should return detailed information about the group - so the caller doesn't need to rely on picking the consumer group id, the server could provide it.
=> improve consumer group creation

.github/workflows/test_pr.yml, Cargo.lock, sdk/Cargo.toml, sdk/src/error.rs, sdk/src/quic/client.rs, server/Cargo.toml, server/src/quic/listener.rs, server/src/quic/quic_sender.rs, server/src/quic/quic_server.rs
Upgrade quinn and rustls to newest available versions. Refactor QUIC
client to use newer rustls APIs and add error handling for incoming
connections in server. Add new error code for QUIC closed stream
errors.
=> Update dependencies and refactor QUIC client/server

.github/workflows/release.yml, .github/workflows/sanity.yml, .github/workflows/test_daily.yml
Removed Linux-arm build from release and nightly workflows. Updated
cargo-machete to v0.6 in sanity workflow. Added new test_daily
workflow for daily tests at 8:00 AM UTC. Adjusted nightly test
schedule to run it at night at 11:00 PM UTC.
=> Remove Linux-arm build, update cargo-machete, add test_daily workflow

Cargo.lock, sdk/Cargo.toml, sdk/src/utils/timestamp.rs, server/Cargo.toml
This commit updates the conversion from IggyTimestamp to u64 to use
microseconds instead of seconds.
=> Change IggyTimestamp conversion to use microseconds

README.md
Updated path for `iggy cli` in `README.md` for local development environment.
While using previously mentioned path for cli `iggy/iggy`:
`% docker exec -it iggy-server /iggy/iggy ping`
`OCI runtime exec failed: exec failed: unable to start container process: exec: "/iggy/iggy": stat /iggy/iggy: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type`
After using the updated path `/iggy`:
`% docker exec -it iggy-server /iggy ping`
```
Executing ping command
Ping sequence id: 1 time: 0.26 ms
Ping statistics for 1 ping commands
min/avg/max/mdev = 0.262/0.262/0.262/0.000 ms
```
=> Update path for iggy cli in README.md

Cargo.lock, cli/Cargo.toml, integration/tests/cli/common/mod.rs, integration/tests/cli/personal_access_token/test_pat_login_options.rs, integration/tests/cli/system/test_cli_session_scenario.rs, integration/tests/cli/system/test_me_command.rs, sdk/src/args.rs, server/Cargo.toml
Use server address with port for CLI session key in keyring and add
localhost replacing localhost with 127.0.0.1 for all protocols. Adapt
intergration tests for this change and bump CLI crate version.
=> Improve CLI login session handling

Cargo.lock, cli/Cargo.toml, cli/src/main.rs, sdk/Cargo.toml, sdk/src/client_provider.rs, server/Cargo.toml
Add new method for creating ClientProviderConfig with possibility
to enable or disable AutoLogin option while creating from Args.
Disabling AutoLogin for CLI.
=> Fix issue with wrong root credentials handling in CLI

.github/workflows/release.yml
Use actions/download-artifact@v4 workflow version and set merge-multiple
flat to true.
=> Set merge-multiple for github release artifact download workflow

.github/workflows/release.yml, Cargo.lock, server/Cargo.toml
Revert to use same version of download-artifact action for the release
to GitHub workflow (same as in docker release workflow). Add pattern
for downloaded artifacts (same set of parameters as in docker release
workflow).
=> Pin download-artifact action to specific version

.github/workflows/test_pr.yml
This PR replaces the use of FlyCI macOS runners with GitHub ones since FlyCI macOS runners will be discontinued effective Sep 30, 2024. 
[Read more about the discontinuation of the FlyCI macOS runners](https://flyci.net/blog/flyci-discontinue-macos-runners?utm_source=site_link&utm_medium=github&utm_campaign=discontinue-runners).
=> Replace FlyCI runners with GitHub runners

.github/workflows/release.yml, Cargo.lock, cli/Cargo.toml, cli/src/args/mod.rs, cli/src/credentials.rs, cli/src/error.rs, cli/src/main.rs, server/Cargo.toml
Add login-session feature to default features for iggy CLI and disable
it for official docker release due to missing keyring storage inside
docker. Updating release workflow to build server and cli separately.
=> Add login-session feature to iggy CLI

.github/workflows/release.yml, Cargo.lock, server/Cargo.toml
Move building x86_64 and aarch64 directly to create_github_release
step in order to fix GitHub release creation. Bump server version
to test new release flow.
=> Drop using artifacts upload and download for release workflow

Cargo.lock, cli/Cargo.toml, cli/src/args/message.rs, cli/src/main.rs, integration/tests/cli/message/mod.rs, integration/tests/cli/message/test_message_flush_command.rs, integration/tests/cli/message/test_message_help_command.rs, sdk/Cargo.toml, sdk/src/cli/message/flush_messages.rs, sdk/src/cli/message/mod.rs
Add new subcommand for flushing messages with optional fsync operation
for flushing of unsaved buffer to disk for specific stream, topic
and partition. Add integration tests for new command.
=> Add message flush command to CLI

Cargo.lock, cli/Cargo.toml, cli/src/args/message.rs, cli/src/main.rs, integration/tests/cli/message/mod.rs, integration/tests/cli/message/test_message_poll_command.rs, integration/tests/cli/message/test_message_poll_to_file_command.rs, sdk/Cargo.toml, sdk/src/cli/message/poll_messages.rs
Add option for message poll command which stores messages in binary
format in given file. This will allow to replay the messages with
message send command. Adapt integration tests to new change.
Improve status message while printing amount of polled messages.
This fixes #648
=> Add option to message poll command to store message in file

Cargo.lock, cli/Cargo.toml, cli/src/args/message.rs, cli/src/main.rs, integration/tests/cli/message/mod.rs, integration/tests/cli/message/test_message_reply_via_file.rs, integration/tests/cli/message/test_message_send_command.rs, integration/tests/cli/message/test_message_send_from_file_command.rs, sdk/Cargo.toml, sdk/src/cli/message/send_messages.rs
Add option for message send command which reads messages from binary
format in given file. This will allow to replay the messages stored
on the server using message poll and message send commands.
Adapt integration tests to new change. Add test scenario to verify
message replay from one topic to another using binary file.
This fixes #647
=> Add option to message send command to send messages from file

Cargo.lock, integration/tests/archiver/disk.rs, server/Cargo.toml, server/src/archiver/disk.rs, server/src/archiver/mod.rs, server/src/archiver/s3.rs, server/src/compat/message_conversion/samplers/message_sampler.rs, server/src/compat/message_conversion/samplers/retained_batch_sampler.rs, server/src/compat/message_conversion/schema_sampler.rs, server/src/compat/message_conversion/snapshots/message_snapshot.rs, server/src/compat/message_conversion/snapshots/retained_batch_snapshot.rs, server/src/configs/config_provider.rs, server/src/configs/server.rs, server/src/configs/validators.rs, server/src/log/logger.rs, server/src/quic/listener.rs, server/src/server_error.rs, server/src/tcp/connection_handler.rs
Replaced thiserror with error_set for ServerError to improve usability and error handling consistency. The transition to error_set not only simplifies the creation of new errors and allows combining them under a common error type, but also provides a convenient mechanism for tracing and logging
=> Migrate ServerError to error_set

Cargo.lock, configs/server.json, configs/server.toml, integration/src/test_server.rs, sdk/Cargo.toml, sdk/src/client.rs, sdk/src/clients/consumer.rs, server/Cargo.toml, server/src/configs/defaults.rs, server/src/configs/tcp.rs, server/src/tcp/mod.rs, server/src/tcp/tcp_listener.rs, server/src/tcp/tcp_server.rs, server/src/tcp/tcp_socket.rs, server/src/tcp/tcp_tls_listener.rs
This PR exposes useful TCP parameters to the user through the configuration
refer to issue #31
=> Expose TCP parameters

.github/workflows/performance.yml, .gitignore, Cargo.lock, bench/Cargo.toml, bench/src/args/common.rs, bench/src/args/kind.rs, bench/src/args/mod.rs, bench/src/args/transport.rs, bench/src/benchmark_params.rs, bench/src/benchmark_result.rs, bench/src/benchmark_runner.rs, bench/src/benchmarks/consumer_group_benchmark.rs, bench/src/benchmarks/poll_benchmark.rs, bench/src/benchmarks/send_and_poll_benchmark.rs, bench/src/benchmarks/send_benchmark.rs, bench/src/consumer.rs, bench/src/main.rs, bench/src/producer.rs, bench/src/statistics/actor_statistics.rs, bench/src/statistics/aggregate_statistics.rs, bench/src/statistics/mod.rs, bench/src/statistics/record.rs, configs/server.toml, scripts/performance/run-standard-performance-suite.sh, scripts/performance/utils.sh, scripts/profile.sh, scripts/run-benches.sh
This commit is a base for future performance testing in CI.
- Set up GitHub workflow to run performance benchmarks on push to master
- Enhance benchmarking tools to collect and serialize detaile statistics,
now iggy-bench can output data to csv and toml files
- Introduce scripts for executing standard performance suites
and handling results - run-standard-performance-suite.sh
- Ensure performance results are properly cached and artifacts are uploaded
Desired outcome of whole feature is be able to present the results of
benchmarks in grafana.
=> Add skeleton for automated performance testing in CI

Cargo.lock, server/Cargo.toml, server/src/streaming/batching/batch_accumulator.rs
Refactor materialize_batch_and_maybe_update_state to use drain for processing message batches, eliminating unnecessary copies of self.messages and enhancing performance.
Iggy bench results for **messages_required_to_save = 1**(via `cargo run --release --bin iggy-bench -- send tcp`)
new function:
```
2024-12-07T15:31:12.909732Z  INFO iggy_bench::benchmark_runner: Results: Total throughput: 971.09 MB/s, 948330 messages/s, average throughput: 97.11 MB/s, average p50 latency: 9.00 ms, average p90 latency: 17.96 ms, average p95 latency: 22.11 ms, average p99 latency: 31.07 ms, average p999 latency: 74.38 ms, average latency: 10.55 ms, median latency: 9.00 ms
```
old:
```
2024-12-07T15:24:44.084381Z  INFO iggy_bench::benchmark_runner: Results: Total throughput: 129.75 MB/s, 126708 messages/s, …
```
=> Improve materialize_batch_and_maybe_update_state

Cargo.lock, integration/tests/streaming/consumer_offset.rs, integration/tests/streaming/messages.rs, sdk/Cargo.toml, sdk/src/quic/client.rs
This commit adds print when rustls crypto provider fails to install.
On top of that itcorrects the logic for iterating over loaded messages in the
`should_persist_messages_and_then_load_them_by_timestamp` test.
Besides that, it adds similar workaround to
`should_persist_consumer_offsets_and_then_load_them_from_disk`.
=> Handle rustls crypto provider install, hack togglers to work

Cargo.lock, server/Cargo.toml, server/src/lib.rs
This commit introduces support for the mimalloc allocator as an optional
feature in the server package. The Cargo.toml and Cargo.lock files have
been updated to include mimalloc and its dependencies. Additionally, the
server version is incremented to 0.4.93.
This closes #1347.
=> Add mimalloc support to iggy-server and make it default allocator for musl env

Cargo.lock, cli/src/main.rs, integration/tests/state/mod.rs, integration/tests/streaming/common/test_setup.rs, sdk/Cargo.toml, sdk/src/clients/builder.rs, sdk/src/clients/client.rs, sdk/src/clients/consumer.rs, sdk/src/clients/producer.rs, sdk/src/utils/crypto.rs, server/Cargo.toml, server/src/http/jwt/jwt_manager.rs, server/src/http/jwt/storage.rs, server/src/state/file.rs, server/src/streaming/partitions/storage.rs, server/src/streaming/persistence/persister.rs, server/src/streaming/persistence/task.rs, server/src/streaming/segments/storage.rs, server/src/streaming/storage.rs, server/src/streaming/systems/storage.rs, server/src/streaming/systems/system.rs, tools/src/data-seeder/main.rs
Addresses part of #https://github.com/iggy-rs/iggy/issues/667
This PR refactors the codebase to replace the use of dyn Trait for Encryptor and Persister with enum types (EncryptorKind and PersisterKind)
=> Refactor: Replace dyn Trait with Enum for Encryptor and Persister Types

Cargo.lock, sdk/Cargo.toml, sdk/src/identifier.rs
This fixes #1456 by ensuring that the named `Identifier` will be set correctly on the client-side. In the future, we might allow the user to provide any name without the additional conversion, case-invariant checks etc.
=> Fix named ID on the client

bench/src/runner.rs
When running bench for older server, which doesn't have
`server_version` field in stats, instead of crashing binary
we just handle it gracefuly.
=> Fix getting server version in iggy-bench

Cargo.lock, bench/Cargo.toml, bench/src/actors/consumer.rs, bench/src/actors/producer.rs, bench/src/analytics/time_series/calculators/latency.rs, bench/src/args/common.rs, bench/src/benchmarks/consumer_group_benchmark.rs, bench/src/benchmarks/poll_benchmark.rs, bench/src/benchmarks/send_and_poll_benchmark.rs, bench/src/benchmarks/send_benchmark.rs, bench/src/main.rs, bench/src/plot.rs, bench/src/rate_limiter/mod.rs, bench/src/runner.rs
This commit introduces a rate limiting feature for both producers and
consumers, allowing users to specify a rate limit in bytes per second.
The rate limiter is implemented using a linger-based algorithm to ensure
smooth throughput control.
Additionally, a new command-line argument is added to open generated
charts in the browser automatically after the benchmark is completed.
The changes also include updates to the latency calculation logic,
switching from average latency to worst latency per bucket for more
accurate performance insights.
=> Add rate limiting and browser chart opening features

Cargo.lock, bench/Cargo.toml, bench/report/Cargo.toml, bench/report/src/plotting/text/subtext.rs, bench/report/src/plotting/text/title.rs, bench/report/src/types/benchmark_kind.rs, bench/report/src/types/params.rs, bench/src/args/common.rs, bench/src/args/kind.rs, bench/src/args/kinds/consumer_group_poll.rs, bench/src/args/kinds/poll.rs, bench/src/args/kinds/send.rs, bench/src/args/kinds/send_and_poll.rs, bench/src/args/props.rs, bench/src/benchmarks/benchmark.rs
This commit introduces a new option to specify the maximum topic size in a human-readable format, such as "1GiB" or "2MB". This allows users to customize the topic size for benchmarks, with the server default being used if not specified. Additionally, the benchmark charts subtext format has been updated to include the number of partitions.
Besides that, commit introduces new benchmark kinds: ConsumerGroupSend and ConsumerGroupSendAndPoll which are not yet implemented.
=> Add max topic size option, improve benchmark output, add new bench kinds

Cargo.lock, bench/Cargo.toml, bench/report/Cargo.toml, bench/report/src/plotting/text/subtext.rs, bench/report/src/prints.rs, bench/report/src/types/group_metrics_summary.rs, bench/report/src/types/individual_metrics_summary.rs, bench/src/actors/consumer.rs, bench/src/actors/producer.rs, bench/src/analytics/metrics/group.rs, bench/src/analytics/metrics/individual.rs, bench/src/args/common.rs, sdk/Cargo.toml, sdk/src/binary/mapper.rs, sdk/src/models/stats.rs, server/Cargo.toml, server/src/binary/mapper.rs, server/src/channels/commands/print_sysinfo.rs, server/src/streaming/cache/buffer.rs, server/src/streaming/partitions/messages.rs, server/src/streaming/partitions/partition.rs, server/src/streaming/systems/stats.rs
This commit introduces cache metrics tracking and p9999 latency measurement to improve performance monitoring and analysis. The `human-repr` crate is added to enhance readability of large numbers in logs and reports.
- Updated `Cargo.toml` and `Cargo.lock` to include `human-repr` dependency.
- Added cache metrics collection and serialization in both client and server.
- Implemented p9999 latency tracking in benchmark reports and analytics.
- Enhanced logging with human-readable counts and sizes using `human-repr`.
- Refactored code to accommodate new metrics and improve clarity.
=> Add cache metrics to `Stats` and p9999 latency tracking to `BenchmarkReport`

Cargo.lock, sdk/Cargo.toml, sdk/src/models/messages.rs, server/Cargo.toml, server/src/streaming/systems/messages.rs, server/src/streaming/topics/consumer_group.rs, server/src/streaming/topics/consumer_offsets.rs, server/src/streaming/topics/topic.rs
This fixes #1478 by returning no messages and none partition ID internally, if there's more consumer group members than the available partitions to be assigned.
=> Fix consumer group member partition assignments for no partitions

Cargo.lock, sdk/Cargo.toml, sdk/src/consumer_groups/create_consumer_group.rs, sdk/src/identifier.rs, sdk/src/models/topic.rs, sdk/src/personal_access_tokens/create_personal_access_token.rs, sdk/src/personal_access_tokens/delete_personal_access_token.rs, sdk/src/streams/create_stream.rs, sdk/src/streams/update_stream.rs, sdk/src/topics/create_topic.rs, sdk/src/topics/update_topic.rs, sdk/src/users/create_user.rs, sdk/src/users/login_user.rs, sdk/src/users/update_user.rs, sdk/src/utils/text.rs, server/Cargo.toml, server/src/streaming/streams/topics.rs, server/src/streaming/systems/personal_access_tokens.rs, server/src/streaming/systems/streams.rs, server/src/streaming/systems/users.rs, server/src/streaming/topics/consumer_groups.rs
Remove the existing convention which would rename the received resource name to lowercase, replace whitespace characters with dots etc. - let the user decide and be responsible for naming the things.
=> Use case-sensitive names for resources such as streams, topics, users etc.

.github/workflows/backwards_compatibility.yml, .github/workflows/post_release.yml
This commit updates the naming conventions in the GitHub workflows for
benchmarking tasks to use "Producer" and "Consumer" instead of "Send" and
"Poll". Additionally, the expected message count in the post-release
workflow has been adjusted from 200,000 to 160,000 to reflect the updated
benchmarking parameters.
This closes #1483.
=> Update benchmark naming and expected message count

Cargo.lock, sdk/Cargo.toml, sdk/src/clients/consumer.rs, sdk/src/clients/producer.rs, sdk/src/error.rs
Adds new method for `IggyProducerBuilder` -> `send_retries()` which allows to specify an optional number of retries and the interval between them, in case of failure when sending the messages (e.g. client disconnection or server rejecting the messages). It also removes the existing `reconnection_retry_interval()` from the builder, and unifies the retries policy under the new method.
=> Extend SDK Producer with optional retries in case of send messages failure

Cargo.lock, bench/src/actors/consumer.rs, server/Cargo.toml, server/src/streaming/segments/messages.rs
The messages_required_to_save config was incorrectly used as batch size limit,
causing messages to be split into smaller batches than requested. This fixes
polling issues where consumers couldn't retrieve their expected batch sizes.
=> Fix polling when batch size is greater than messages_required_to_save

bench/report/src/prints.rs, bench/report/src/types/benchmark_kind.rs, bench/report/src/types/params.rs, bench/src/actors/consumer.rs, bench/src/actors/producing_consumer.rs, bench/src/args/common.rs, bench/src/args/defaults.rs, bench/src/args/examples.rs, bench/src/args/kind.rs, bench/src/args/kinds/balanced/consumer_group.rs, bench/src/args/kinds/end_to_end/mod.rs, bench/src/args/kinds/end_to_end/producer_and_consumer_group.rs, bench/src/args/kinds/end_to_end/producing_consumer.rs, bench/src/args/kinds/end_to_end/producing_consumer_group.rs, bench/src/args/output.rs, bench/src/args/props.rs, bench/src/args/transport.rs, bench/src/benchmarks/benchmark.rs, bench/src/benchmarks/mod.rs, bench/src/benchmarks/producing_consumer_benchmark.rs, bench/src/benchmarks/producing_consumer_group_benchmark.rs, bench/src/runner.rs, server/src/streaming/partitions/messages.rs
This commit introduces the `EndToEndProducingConsumerGroup` benchmark, which
allows for benchmarking scenarios with producing consumers assigned to multiple
consumer groups. Key changes include:
- Added `EndToEndProducingConsumerGroup` to the `BenchmarkKind` enum.
- Implemented the `ProducingConsumer` actor to handle producing and consuming
messages within consumer groups.
- Updated command-line arguments to support the new benchmark type.
- Modified existing benchmarks to accommodate the new consumer group logic.
- Improved logging and error handling for better traceability during execution.
=> Implement EndToEndProducingConsumerGroup Benchmark

Cargo.lock, bench/Cargo.toml, configs/server.toml, integration/tests/server/scenarios/system_scenario.rs, server/Cargo.toml, server/src/lib.rs
This commit integrates the mimalloc allocator as the default feature for
both the bench and server packages, aiming to improve memory allocation
performance. The `messages_required_to_save` configuration in
`server.toml` is reduced from 5000 to 1000 to enhance performance. by
Additionally, the server version is bumped from 0.4.151 to 0.4.152 to
reflect these changes.
=> Add mimalloc allocator and adjust message save threshold

server/src/args.rs, server/src/main.rs
This commit introduces a new `--fresh` flag to the server's command-line
arguments. When this flag is set, the server will remove the system path
(local_data by default) before starting, effectively clearing all saved
data. This is useful for starting with a clean state.
=> Add `--fresh` flag to remove system path before starting

Cargo.lock, configs/server.toml, integration/tests/server/scenarios/system_scenario.rs, server/Cargo.toml
There is unknown (yet) bug in server which makes it work unpredictably bad when mentioned value is set to 1000.
=> Change messages required to save back to 5000

.github/workflows/post_publish_server.yml, .github/workflows/publish_server.yml, .github/workflows/release_server.yml
Rename release CI workflow to publish_server and extract from that
flow step for GitHub release creation to release_server workflow
file which is triggered when server tag is created.
This fix #1517
=> chore(ci): rename release workflow and add new release_server

.github/workflows/coverage.yml
If pull request contains 'skip-coverage' label, skip publish data
to coveralls.
=> chore(ci): skip publishing coverage to coveralls when label is set

Cargo.lock, server/Cargo.toml, server/src/streaming/cache/buffer.rs, server/src/streaming/local_sizeable.rs, server/src/streaming/models/messages.rs
This commit refactors the cache size calculation by replacing the
`LocalSizeable` trait with a new `RealSize` trait. The `RealSize`
trait provides a more accurate calculation of the memory size of
types, including overhead from containers like `Arc` and `Vec`.
=> refactor(server): improve cache size calculation and memory tracking

.github/workflows/publish_server.yml, .github/workflows/release_server.yml
Change release_server workflow to workflow_call and trigger
the execution from publish_server workflow with server git tag
name as a parameter.
=> chore(ci): fix github release creation trigger

Cargo.lock, configs/server.toml, integration/tests/cli/topic/test_topic_create_command.rs, integration/tests/cli/topic/test_topic_get_command.rs, integration/tests/cli/topic/test_topic_update_command.rs, integration/tests/server/scenarios/system_scenario.rs, sdk/src/utils/topic_size.rs, server/Cargo.toml, server/src/channels/commands/maintain_messages.rs, server/src/streaming/segments/logs/log_writer.rs, server/src/streaming/segments/segment.rs, server/src/streaming/segments/writing_messages.rs, server/src/streaming/topics/messages.rs
This commit addresses a panic issue that occurred during segment deletion
and closure by ensuring proper shutdown of reading and writing tasks. It
also improves the handling of maximum topic size by allowing unlimited
size and ensuring that the oldest segments are removed by a background
job when necessary. Additionally, the logging level for certain operations
has been adjusted to provide more detailed trace information. These changes
enhance the stability and flexibility of the system in managing topic
segments and their lifecycle.
=> fix(server): don't panic during segment deletion, improve max topic size

Cargo.lock, integration/tests/streaming/common/test_setup.rs, server/Cargo.toml, server/src/streaming/partitions/messages.rs, server/src/streaming/partitions/partition.rs, server/src/streaming/segments/logs/log_writer.rs, server/src/streaming/segments/logs/persister_task.rs, server/src/streaming/streams/stream.rs, server/src/streaming/streams/topics.rs, server/src/streaming/systems/streams.rs, server/src/streaming/topics/consumer_groups.rs, server/src/streaming/topics/messages.rs, server/src/streaming/topics/topic.rs
This commit  optimizes the log writing process by removing the
`stream_position()` call, which uses `lseek` and negatively
impacts performance. Afterwards, the new implementation
directly updates the log file size using `fetch_add`, resulting
in a 40% performance improvement on writing (Linux).
On MacOS, degradation was not visible.
=> perf(server): optimize writing performance

.github/workflows/test_pr.yml, server/src/lib.rs
This commit removes Windows support for the server by
introducing a compile-time error for Windows platforms.
The GitHub Actions workflow has been updated to separate
the build and test processes for Linux and Windows,
ensuring that the server is not built on Windows.
This change is needed due to lack of `read_at` support on
windows and upcoming thread per core architecture changes.
=> chore(ci): remove Windows support for `iggy-server`

Cargo.lock, server/Cargo.toml, server/src/compat/index_rebuilding/index_rebuilder.rs, server/src/streaming/batching/batch_accumulator.rs, server/src/streaming/batching/message_batch.rs, server/src/streaming/segments/indexes/index_reader.rs, server/src/streaming/segments/indexes/index_writer.rs, server/src/streaming/segments/logs/log_reader.rs, server/src/streaming/segments/logs/log_writer.rs, server/src/streaming/segments/logs/persister_task.rs, server/src/streaming/segments/writing_messages.rs
This commit addresses a deadlock issue in file reading operations by
refactoring the code to use `Arc<File>` instead of `RwLock<Option<File>>`.
The changes ensure that file operations are performed in a non-blocking
manner using `spawn_blocking` and `read_exact_at`. This improves the
concurrency and efficiency of file access, particularly in scenarios
where multiple tasks are reading from the same file concurrently. The
commit also includes error handling improvements for better diagnostics
and robustness.
Besides that, `posix_fadvise(sequential)` is added for segment files
to improve page cache utilization.
=> fix(server): resolve deadlock during concurrent segment reads

Cargo.lock, server/Cargo.toml, server/src/streaming/segments/indexes/index_reader.rs, server/src/streaming/segments/logs/log_reader.rs
This commit updates the log level from `warn` to `trace` for messages
indicating that index or log files are empty. This change is made to
reduce the verbosity of warnings in the logs when encountering empty
files, which may be a normal condition in some scenarios.
=> fix(server): change log level from warn to trace for empty file checks

Cargo.lock, cli/Cargo.toml, cli/src/args/topic.rs, integration/tests/cli/topic/test_topic_create_command.rs, integration/tests/cli/topic/test_topic_update_command.rs, sdk/src/cli/topics/update_topic.rs, sdk/src/utils/expiry.rs, server/src/streaming/topics/topic.rs
This commit updates the CLI and associated tests to use "server_default"
as the default value for max topic size and message expiry time, instead
of "unlimited". This change ensures that the CLI uses the server's
default configuration when parameters are not explicitly specified by
the user. Additionally, the commit modifies the display and parsing
logic for `IggyExpiry` to use "never_expire" instead of "none" for
clarity. The tests have been updated to reflect these changes, ensuring
that the new defaults are correctly applied and tested.
This closes #1536.
=> fix(cli): update CLI and tests for server default parameters

.github/workflows/test_pr.yml, Cargo.lock, bench/Cargo.toml, cli/Cargo.toml, examples/Cargo.toml, integration/Cargo.toml, integration/tests/cli/common/command.rs, integration/tests/cli/common/mod.rs, integration/tests/cli/system/mod.rs, sdk/Cargo.toml, sdk/src/messages/send_messages.rs, server/Cargo.toml, server/src/streaming/segments/logs/log_reader.rs, tools/Cargo.toml
This commit modifies the `Display` implementation for the
`SendMessages` struct to include batch length and batch size
in the output instead of raw payload data of message, so
stdout isn't overflown with useless data.
=> chore(sdk): update SendMessages Display, update deps

Cargo.lock, server/Cargo.toml, server/src/streaming/batching/batch_accumulator.rs, server/src/streaming/segments/indexes/index.rs, server/src/streaming/segments/indexes/index_reader.rs, server/src/streaming/segments/reading_messages.rs, server/src/streaming/segments/writing_messages.rs
This commit refactors the `BatchAccumulator` by removing the
`capacity` field and simplifying the logic for materializing
batches. The `materialize_batch_and_maybe_update_state` method
is renamed to `materialize_batch_and_update_state`, and the
logic for handling message offsets and timestamps is streamlined.
The changes improve the clarity and efficiency of the batch processing
logic, addressing issues with the previous handling of `has_remainder`.
Additionally, the logic in `writing_messages.rs` is updated to reflect
these changes, ensuring that unsaved messages are correctly managed
based on batch size.
Now, instead of having hard-limit of `messages_required_to_save` we
will trigger it once when capacity if exceeded and save all messages
on disk, instead of handling remainder.
=> fix(server): correct batch materialization logic in BatchAccumulator

Cargo.lock, server/Cargo.toml, server/src/streaming/segments/segment.rs
This commit addresses an issue with the calculation of the current
offset in the segment when the index cache is disabled. Previously,
the logic incorrectly handled the absence of cached indexes,
potentially leading to incorrect offset values.
The updated logic ensures that the current offset is accurately
calculated regardless of the cache setting, improving the reliability
of segment handling.
=> fix(server): corrent current offset when index cache is disabled

Cargo.lock, bench/Cargo.toml, bench/report/src/prints.rs, bench/src/args/common.rs, bench/src/args/kind.rs, scripts/performance/run-standard-performance-suite.sh, scripts/performance/utils.sh, scripts/utils.sh
This commit enhances the performance scripts by:
- Using `pgrep -x` for exact process name matching to avoid
unintended matches.
- Introducing `wait_for_process_pid` to wait for a specific
PID to exit.
- Modifying the server start and stop logic to use the
correct PID.
- Adding informative messages for process status checks.
- Ensuring graceful termination of processes with specific
'PIDs.
- Improving the robustness of the script by handling
potential race conditions.
- Adding new benchmark for single producer/consumer with
enabled fsync and rate-limiter.
Besides that, improved print at the end of benchmark by adding
total time.
=> fix(ci): improve process management in performance scripts

Cargo.lock, integration/Cargo.toml, integration/tests/streaming/get_by_offset.rs, integration/tests/streaming/get_by_timestamp.rs, integration/tests/streaming/messages.rs, integration/tests/streaming/mod.rs, server/Cargo.toml, server/src/streaming/partitions/messages.rs, server/src/streaming/segments/indexes/index_reader.rs, server/src/streaming/segments/mod.rs, server/src/streaming/segments/segment.rs
This commit refactors the `get_messages_by_timestamp` function
to improve efficiency and readability. The changes include:
- Simplified logic for finding the starting segment and offset.
- Removed unnecessary calculations and variables.
- Enhanced error handling with more detailed context.
- Improved message filtering and collection logic.
- Removed redundant functions and code for better maintainability.
Besides that, added additional 288 testcases that test both
`get_messages_by_timestamp` and `get_messages_by_offset` to improve
robustness of iggy-server.
=> fix(server): fix `get_messages_by_timestamp` logic

.github/workflows/release_cli.yml, Cargo.lock, cli/Cargo.toml
Add more target platforms for github cli binary release including
Windows and MacOS. Drop finalize_release from release_cli.yml
as the workflow is used as workflow call and status is checked
on caller level. Bump cli version to trigger test release.
=> chore(ci,cli): extend cli github release with more architectures

.github/workflows/release_cli.yml, Cargo.lock, cli/Cargo.toml
Correct build command to make sure iggy binary is build.
This fix #1564 #1565
=> chore(ci,cli): fix github cli release

Cargo.lock, server/Cargo.toml, server/src/binary/handlers/consumer_groups/create_consumer_group_handler.rs, server/src/binary/handlers/consumer_groups/delete_consumer_group_handler.rs, server/src/binary/handlers/partitions/create_partitions_handler.rs, server/src/binary/handlers/partitions/delete_partitions_handler.rs, server/src/binary/handlers/personal_access_tokens/create_personal_access_token_handler.rs, server/src/binary/handlers/personal_access_tokens/delete_personal_access_token_handler.rs, server/src/binary/handlers/streams/create_stream_handler.rs, server/src/binary/handlers/streams/delete_stream_handler.rs, server/src/binary/handlers/streams/update_stream_handler.rs, server/src/binary/handlers/topics/create_topic_handler.rs, server/src/binary/handlers/topics/delete_topic_handler.rs, server/src/binary/handlers/topics/update_topic_handler.rs, server/src/binary/handlers/users/change_password_handler.rs, server/src/binary/handlers/users/create_user_handler.rs, server/src/binary/handlers/users/delete_user_handler.rs, server/src/binary/handlers/users/update_permissions_handler.rs, server/src/binary/handlers/users/update_user_handler.rs, server/src/http/consumer_groups.rs, server/src/http/partitions.rs, server/src/http/personal_access_tokens.rs, server/src/http/streams.rs, server/src/http/topics.rs, server/src/http/users.rs
This commit refactors the handling of system write and read
operations by removing unnecessary scopes and using `downgrade()`
instead of `read().await`.
This change reduces potential deadlocks.
=> fix(server): refactor system write and read operations

Cargo.lock, cli/Cargo.toml
Add binstall section to iggy-cli Cargo.toml to allow users to
use cargo binstall or cargo install-update and fetch binary
artefacts from iggy official ci release. Bump cli version
for testing purposes.
=> chore(ci, cli): add to cli configuration support for binstall

Cargo.lock, integration/tests/streaming/get_by_offset.rs, integration/tests/streaming/get_by_timestamp.rs, integration/tests/streaming/messages.rs, integration/tests/streaming/segment.rs, sdk/Cargo.toml, sdk/src/utils/timestamp.rs, server/Cargo.toml, server/src/streaming/batching/batch_accumulator.rs, server/src/streaming/partitions/messages.rs, server/src/streaming/segments/reading_messages.rs, server/src/streaming/segments/segment.rs, server/src/streaming/segments/writing_messages.rs
This commit fixed functionality to retrieve messages by timestamp
when all messages are stored in the unsaved buffer. The changes include
modifications to the `BatchAccumulator` and `Segment` structs to handle
timestamp-based retrieval efficiently. The `get_messages_by_timestamp`
method has been added to both strcuts, allowing for precise message
retrieval based on timestamps.
=> fix(server): correct getting messages by timestamp from unsaved_buffer

.github/workflows/coverage.yml, .github/workflows/post_publish_server.yml, .github/workflows/publish_cli.yml, .github/workflows/publish_sdk.yml, .github/workflows/publish_server.yml, .github/workflows/release_cli.yml, .github/workflows/release_server.yml, .github/workflows/sanity.yml, .github/workflows/security.yml, .github/workflows/test_daily.yml, .github/workflows/test_nightly.yml, .github/workflows/test_pr.yml, integration/tests/cli/personal_access_token/mod.rs, integration/tests/cli/system/mod.rs
Update version to major only for all actions with detailed version
specifier. Replaced dtolnay/rust-toolchain with actions-rs/toolchain.
Replaced clechasseur/rs-cargo with actions-rs/cargo.
Replaced bnjbvr/cargo-machete with taiki-e/install-action for
cargo-machete installation.
=> chore(ci): update GitHub Actions to use latest versions

.asf.yaml
Add the initial version of `.asf.yaml` infrastructure config, to define the branch protection rules and integrate the discussions with a mailing list.
=> chore(repo): add .asf for Apache infrastructure

.github/dependabot.yml
Updated the assignees and reviewers in the dependabot configuration
file from "iggy-rs/maintainers" to "apache/iggy-committers" for both
the GitHub Actions and Cargo package ecosystems. This change ensures
that the appropriate team members are notified and can review the
dependency updates.
=> chore(ci): update assignees and reviewers

.github/workflows/backwards_compatibility.yml, .github/workflows/coverage.yml, .github/workflows/performance.yml, .github/workflows/post_publish_server.yml, .github/workflows/publish_server.yml, .github/workflows/release_cli.yml, .github/workflows/test_daily.yml, .github/workflows/test_nightly.yml, .github/workflows/test_pr.yml
Modified cache keys in each workflow to be more descriptive and
specific to the job, improving cache management and reducing
potential cache conflicts. Removed redundant cache steps in
release_cli.
=> chore(ci): update CI workflows rust-cache version and key

.github/workflows/publish_cli.yml, .github/workflows/publish_sdk.yml, .github/workflows/publish_server.yml
Replace trigger to tag push and add checks to verify if the tag
name matches version set in corresponding Cargo.toml files.
Skip docker publish steps in server release if not run as release
(tag push) workflow.
=> chore(ci): change trigger event for release workflows

.convco, .github/workflows/ci-check-common.yml, .github/workflows/ci-check-pr.yml, .github/workflows/ci-check-rust.yml, .github/workflows/ci-check-shell.yml, .github/workflows/ci-compatibility-rust.yml, .github/workflows/ci-coverage-rust.yml, .github/workflows/ci-test-rust-optional.yml, .github/workflows/ci-test-rust.yml, .github/workflows/test_pr.yml, scripts/performance/run-standard-performance-suite.sh
Add new set of GitHub workflow files for pull request validation with re-designed flow and added checks. For now it will run in parallel with existing flow for testing purposes.
Change introduce .convco for scope regex for conventional commits validation. It adds ci-check-common.yml for commit message validation. Add ci-check-pr.yml as a main workflow to validate PRs with conditional jobs for Rust and shell changes. Include ci-check-rust.yml for Rust checks and ci-check-shell.yml for shell script validation. Rename and update compatibility and coverage workflows. Add optional Rust test workflow for aarch64-apple-darwin. Update performance script with shellcheck directives. Ensure all workflows are documented and are licensed under Apache License 2.0.
=> chore(ci): add new CI workflows for PR validation and testing

.github/workflows/post_publish_server.yml, .github/workflows/publish_server.yml
Fix the names of envs used in workflow to publish the iggy server image to DockerHub.
=> chore(ci): update envs for docker image release

.github/workflows/publish_server.yml
Skip release conditions for docker steps in publish_server workflow in order to allow iggy docker image preparation for each merged commit under edge tag in dockerhub repo.
=> chore(ci): allow docker workflow actions for each commit

.github/workflows/ci-prod-rust.yml, .github/workflows/ci-prod.yml
Add production flow triggered on push to master branch with new Rust specific flow which triggers Docker image creation for x86_64 and aarch64 architectures with edge tag release to Docker Hub.
=> chore(ci): add production workflow with Rust specific flow

.github/workflows/ci-prod-rust.yml, .github/workflows/ci-prod.yml
Pass DockerHub secrets from main production (on push) workflow
to Rust workflow for creating images with iggy server.
=> fix(ci): pass DockerHub secrets to Rust production workflow

.convco
**Please remove this entire section before submitting your PR.**
**This section is only for your reference.**
🙌 **Thank you for contributing to `iggy`!**
To help us incorporate your changes efficiently, please adhere to the following guidelines:
- **Code Formatting**: Run `cargo fmt` to ensure your code adheres to the project's style.
- **Code Linting**: Run `cargo clippy --all-targets --all-features -- -D warnings` to make sure your code is lint-free.
- **Unit Testing**: Write or update unit tests to cover your changes.
- **Integration Testing**: Write or update integration tests to cover your changes.
- **Project Structure**: Follow the `iggy` project's structure and coding style.
- **Build Integrity**: Ensure your code compiles and runs error-free.
- **Check unused dependencies**: Run …
=> chore(ci): add more CI workflows for PR validation

.github/dependabot.yml
Set cargo updates to weekly and add grouping for cargo
updates so that minor and patch updates are grouped
together while for major changes individual pull requests
are created. Dropping GitHub actions updates in order
to align with planned Apache strategy for GitHub actions.
=> chore(ci): change dependabot schedule and add grouping

Cargo.lock, bench/Cargo.toml, bench/report/Cargo.toml, cli/Cargo.toml, examples/Cargo.toml, sdk/Cargo.toml, server/Cargo.toml, server/src/binary/handlers/personal_access_tokens/create_personal_access_token_handler.rs, server/src/binary/mapper.rs, server/src/channels/commands/clean_personal_access_tokens.rs, server/src/http/mapper.rs, server/src/http/personal_access_tokens.rs, server/src/main.rs, server/src/streaming/personal_access_tokens/personal_access_token.rs, server/src/streaming/systems/info.rs, server/src/streaming/systems/personal_access_tokens.rs, server/src/streaming/systems/storage.rs, server/src/streaming/systems/users.rs, server/src/streaming/users/user.rs, tools/Cargo.toml
Remove the write lock when running the personal access token cleaner, use Dashmap for PAT instead.
Update all dependencies, and log commit hash info during server startup.
=> fix(server): use dashmap for personal access tokens, log commit hash info

sdk/src/error.rs, server/src/streaming/streams/storage.rs, server/src/streaming/systems/streams.rs, server/src/streaming/topics/storage.rs
When the resource such as stream, topic or partition is removed from disk (e.g. accidentally), but not from the server state log, the server should not panic.
=> fix(server): do not terminate the server when state resource is missing

.github/workflows/publish_cli.yml, .github/workflows/publish_sdk.yml, .github/workflows/publish_server.yml
Since GitHub Actions do not use the regex syntax, but glob patterns instead, the tag-based release trigger needs to be fixed.
=> fix(ci): fix release when pushing the tags

CONTRIBUTING.md, README.md
Learn from opendal's documentation and add contribution documentation to iggy
=> chore(docs): add contributing guide

core/sdk/src/tcp/tcp_client.rs
When the connection fails, we can print a more detailed error log to let the user know how to solve it.
=> chore(server): print more detailed error log when connection fails

Cargo.lock, Cargo.toml, core/bench/Cargo.toml, core/bench/report/Cargo.toml, core/binary_protocol/Cargo.toml, core/cli/Cargo.toml, core/common/Cargo.toml, core/examples/Cargo.toml, core/integration/Cargo.toml, core/sdk/Cargo.toml, core/server/Cargo.toml, core/server/src/streaming/segments/messages/messages_reader.rs, core/tools/Cargo.toml
This commit refactors all Cargo.toml files to utilize workspace dependencies,
streamlining dependency management across the project. By centralizing
dependencies, it reduces redundancy and potential version conflicts,
ensuring consistency and simplifying updates.
=> chore(repo): refactor Cargo.toml files to use workspace dependencies

core/integration/tests/examples/mod.rs
According to the code, the server should be started in IggyExampleTest::new() instead of setup
testing
=> fix(test): Fix error logging in integration sample tests

core/integration/src/test_server.rs
1. Delete unnecessary header file references in test_server
2. Delete unnecessary clone
=> chore(test): delete redundant code of test_server

core/common/src/error/iggy_error.rs, core/connectors/runtime/src/source.rs, core/examples/src/multi-tenant/producer/main.rs, core/examples/src/new-sdk/producer/main.rs, core/examples/src/sink-data-producer/main.rs, core/sdk/src/clients/mod.rs, core/sdk/src/clients/producer.rs, core/sdk/src/clients/producer_builder.rs, core/sdk/src/clients/producer_config.rs, core/sdk/src/clients/producer_dispatcher.rs, core/sdk/src/clients/producer_error_callback.rs, core/sdk/src/clients/producer_sharding.rs, core/sdk/src/prelude.rs, core/sdk/src/stream_builder/build/build_iggy_producer.rs
These changes address issues raised during the review https://github.com/apache/iggy/pull/1838#discussion_r2132133626
The following was done:
- Introduced a constant(MIB) for the value `1_048_576`
- Increased the maximum shard count (from 16 to 64)
- Added additional logging when messages are accepted in a shard
- Changed the `cause` type in `ProducerSendFailed` from `String` to `IggyError`
- Renamed the `sync` module to `direct`
- Added extra argument logging in `LogErrorCallback`
=> refactor(sdk): rename sync configuration to direct

.github/workflows/security.yml, Cargo.lock, core/integration/Cargo.toml, core/integration/src/test_server.rs, core/integration/tests/server/scenarios/stream_size_validation_scenario.rs
Remove explicit tracing initialization from integration tests and
stdout printing thread that were bypassing cargo test's output
capture. Also fix rustup command in security workflow to use
correct --component syntax instead of --components.
=> chore(ci): fix test output capture and rustup command syntax

core/integration/tests/server/tcp_server.rs
Refactor data integrity test to verify server restart behavior with
different IGGY_SYSTEM_SEGMENT_CACHE_INDEXES settings. The test now
validates three cache configurations: 'open_segment', 'all', and
'none' to ensure data persistence works correctly regardless of the
index caching strategy.
=> refactor(server): add segment cache index variants to server restart test

README.md, core/server/src/args.rs, examples/rust/README.md
- Enhanced iggy-server help command with comprehensive information:
- Added project description, repository links, and website
- Included configuration examples (TOML file and environment variables)
- Added transport protocols overview (TCP, QUIC, HTTP)
- Provided getting started guide with sample commands
- Improved argument descriptions with detailed examples
- Updated main README.md:
- Added reference to --help command for configuration options
- Included environment variable configuration examples
- Enhanced server startup documentation
- Updated examples/rust/README.md:
- Added help command reference for server configuration
- Included environment variable customization examples
Closes #475
=> chore(docs): extend iggy-server --help command and update documentation

core/integration/src/http_client.rs, core/integration/src/quic_client.rs, core/integration/src/tcp_client.rs, core/integration/src/test_server.rs, core/integration/tests/cli/common/mod.rs, core/integration/tests/sdk/producer/background.rs, core/integration/tests/server/specific.rs, core/sdk/src/client_provider.rs, core/sdk/src/client_wrappers/binary_client.rs, core/sdk/src/client_wrappers/binary_consumer_group_client.rs, core/sdk/src/client_wrappers/binary_consumer_offset_client.rs, core/sdk/src/client_wrappers/binary_message_client.rs, core/sdk/src/client_wrappers/binary_partition_client.rs, core/sdk/src/client_wrappers/binary_personal_access_token_client.rs, core/sdk/src/client_wrappers/binary_segment_client.rs, core/sdk/src/client_wrappers/binary_stream_client.rs, core/sdk/src/client_wrappers/binary_system_client.rs, core/sdk/src/client_wrappers/binary_topic_client.rs, core/sdk/src/client_wrappers/binary_user_client.rs, core/sdk/src/client_wrappers/client_wrapper.rs, core/sdk/src/client_wrappers/mod.rs, core/sdk/src/clients/binary_consumer_group.rs, core/sdk/src/clients/client.rs, core/sdk/src/clients/client_builder.rs, core/sdk/src/clients/consumer.rs, core/sdk/src/clients/consumer_builder.rs, core/sdk/src/clients/producer.rs, core/sdk/src/clients/producer_builder.rs, core/sdk/src/prelude.rs
Replace `Box<dyn Client>` trait objects with a concrete `ClientWrapper` enum to eliminate dynamic dispatch overhead and reduce heap allocations.
By leveraging match-based delegation in `ClientWrapper`, we can eliminate dynamic dispatch and `Box` allocations for client instances. The enum is stack-allocated, compared to heap-allocated Box, saving heap memory.
The `ClientWrapper` enum currently contains Http, Tcp, Quic, and Iggy variants. Future protocol implementations should be added as new variants.
This change serves as a V2 implementation and alternative to the approach in #1912. As discussed, using pure static dispatch would alter too many use case behaviors and require users to have deeper API knowledge. With the enum wrapper, no API changes are needed, benefiting `IggyClient, …
=> perf(sdk): replace Box<dyn Client> with ClientWrapper enum

core/server/src/binary/handlers/messages/send_messages_handler.rs, core/server/src/streaming/utils/memory_pool.rs, core/server/src/streaming/utils/pooled_buffer.rs
Replace unsafe set_len() with slice() for reading exact buffer sizes.
This fixes hangs when memory pool returns larger buffers than requested.
Following compio's recommended pattern: buffer.slice(0..exact_size).
=> fix(io_uring): fix buffer reading with memory pool enabled

core/configs/server.toml, core/server/src/binary/handlers/topics/update_topic_handler.rs, core/server/src/bootstrap.rs, core/server/src/configs/defaults.rs, core/server/src/configs/mod.rs, core/server/src/configs/sharding.rs, core/server/src/configs/system.rs, core/server/src/configs/validators.rs, core/server/src/main.rs, core/server/src/shard/mod.rs, core/server/src/shard/system/topics.rs
- Add system.sharding.cpu_allocation config to control thread-to-CPU mapping
- Support "all" (default), numeric (e.g. 4), and range (e.g. "5..8") values
- Always pin threads to specific CPU cores for consistent performance
- Validate configuration against available CPU cores with descriptive errors
=> feat(io_uring): add configurable CPU sharding with validation

core/integration/tests/data_integrity/verify_after_server_restart.rs, core/integration/tests/server/scenarios/encryption_scenario.rs, core/integration/tests/server/scenarios/mod.rs, core/server/src/streaming/systems/messages.rs
When messages are encrypted, their payload size changes. During
decryption, the server was not updating the message header with
the new (decrypted) payload length, causing the client to
incorrectly parse the message stream and only return 1 message
instead of the full batch.
=> fix(server): update message header with decrypted payload length

Cargo.lock, Cargo.toml, core/server/Cargo.toml, core/server/src/http/consumer_groups.rs, core/server/src/http/consumer_offsets.rs, core/server/src/http/diagnostics.rs, core/server/src/http/http_server.rs, core/server/src/http/http_shard_wrapper.rs, core/server/src/http/jwt/cleaner.rs, core/server/src/http/jwt/storage.rs, core/server/src/http/messages.rs, core/server/src/http/metrics.rs, core/server/src/http/mod.rs, core/server/src/http/partitions.rs, core/server/src/http/personal_access_tokens.rs, core/server/src/http/shared.rs, core/server/src/http/streams.rs, core/server/src/http/system.rs, core/server/src/http/topics.rs, core/server/src/http/users.rs, core/server/src/shard/mod.rs, core/server/src/shard/system/partitions.rs, core/server/src/shard/system/streams.rs, core/server/src/shard/system/topics.rs, core/server/src/shard/system/users.rs, core/server/src/streaming/clients/client_manager.rs, core/server/src/streaming/session.rs, core/server/src/tcp/tcp_socket.rs
Fixes the broken HTTP server by migrating from tokio to compio-based implementation and restricting execution to shard 0 only.
Key Changes:
- Migrate HTTP server to use `compio` and `cyper-axum`.
- Restrict HTTP server to run only on shard 0 to prevent resource duplication across shards
- Introduce `HttpSafeShard` type which wraps over IggyShard to make it `Send + Sync` in http server context.
- Update all HTTP handlers to use `SendWrapper` due to axum interface requiring `Send`. 
- Simplify `Session` by removing atomic operations.
- Update dependencies to use fork versions of compio and cyper libraries to solve panic issue.
- Fix user_id to current one instead of returned previous value by `fetch_add`. This is probably not correct. But works for now.
- Fix partitions, streams, topics …
=> Fix HTTP server using `compio`, `cyper` and restrict to shard 0

core/sdk/src/clients/client.rs, core/sdk/src/clients/client_builder.rs, core/sdk/src/tcp/tcp_client.rs
Currently some comments are missing or repeated for the methods under `IggyClient`.
Make the following changes to make the comments of `IggyClient` more complete.
* Clarify comments for `IggyClient::builder_from_connection_string()`
* Add comment for `IggyClient::from_connection_string()`
=> chore(sdk): Refine comments for methods under `IggyClient`

.github/changed-files-config.json, Dockerfile, Dockerfile.debug, bdd/Dockerfile
After the most recent push to `rust:1.89` tests fail when trying to run iggy-server in docker compose with a missing glibc issue. This changes to use a alpine image instead so we get a musl build.
=> chore: update Dockerfiles to build iggy-server on alpine

bdd/go/tests/tcp_test/offset_feature_deserialize.go, foreign/go/binary_serialization/binary_response_deserializer.go
Added integration tests for consumer offset scenarios and payload validation in `DeserializeOffset` to prevent slice bounds panics with empty payloads.
Changes:
* Integration tests: Cover empty payload, success scenario, and error cases for consumer offset
operations
* Payload validation: Added length check in DeserializeOffset to return nil instead of panicking on
empty payloads
=> fix(go): check payload length in DeserializeOffset

.github/workflows/publish.yml, scripts/copy-latest-from-master.sh
Replace directory existence check with automatic creation using
`mkdir -p` to ensure all files are copied even when destination
directories don't exist.
=> fix(ci): auto-create directories in copy-latest-from-master.sh

.github/actions/utils/docker-buildx/action.yml
Only if `rust-toolchain.toml` is not present.
=> fix(ci): use `1.89` as default Rust version instead of `unknown`

.github/config/components.yml, .github/workflows/publish.yml, core/ai/mcp/Dockerfile, core/connectors/runtime/Dockerfile, core/server/Dockerfile
- Add IGGY_CI_BUILD env to Rust Dockerfiles for git/build info
- Remove bdd-suite component to prevent duplicate test runs
- Fix publish workflow: apply copy-latest-from-master.sh to
create-tags and summary jobs for old code releases
- Ensures scripts/extract-version.sh available when needed
=> fix(ci): remove duplicated bdd tests, handle IGGY_CI_BUILD

core/integration/tests/config_provider/mod.rs, core/server/src/configs/config_provider.rs
- Support array element overrides via env vars (e.g., IGGY_CLUSTER_NODES_0_ID)
- Preserve existing array data when doing partial overrides
- Handle both nested dict and array patterns correctly
- Add comprehensive tests for cluster config array overrides
- Refactor config provider for better maintainability
=> feat(server): add environment variable support for array config overrides

.github/workflows/_build_python_wheels.yml, .github/workflows/publish.yml
Python wheel builds were incorrectly using master HEAD instead of the specified release commit when use_latest_ci=true. Added commit parameter to _build_python_wheels.yml workflow to ensure wheels are built from the intended release commit, matching behavior of other SDK builds.
=> fix(ci): build Python wheels from correct commit instead of master HEAD

README.md
Currently Iggy support automatically generated password for default root user "iggy" when no custom root user credential is provided. Update README so users will know they need to set their own custom root user credentials with environment variables, and iggy's command will not success when providing "-u iggy -p iggy" if users didn't set it explicitly.
=> chore(docs): Update quick start examples to match automatic generated password

core/server/src/shard/system/consumer_offsets.rs, core/server/src/shard/system/messages.rs, core/server/src/shard/system/snapshot/mod.rs, core/server/src/shard/system/streams.rs, core/server/src/shard/system/users.rs, core/server/src/streaming/topics/helpers.rs
- Fix consumer_offsets to use with_partition_by_id directly
- Move calculate_partition_id_by_messages_key_hash to topics helpers
- Refactor purge_stream2 to use purge_stream2_base helper
- Remove unnecessary user lookup in logout_user_base
- Replace Arc with references in snapshot functions
- Document snapshot thread pool limitation
=> fix(server): resolve TODOs and optimize reference usage
