apache/iggy

Cargo.lock
server/Cargo.toml
server/src/main.rs
server/tests/common/mod.rs

Added reaction to SIGTERM and flushing logs
upon receiving shutdown signal. Updated
some packages due to security vulnerability.

Improve shutdown

---

Cargo.lock
server/Cargo.toml
server/src/binary/command.rs
server/src/binary/handlers/streams/delete_stream_handler.rs
server/src/binary/handlers/streams/update_stream_handler.rs
server/src/binary/handlers/topics/create_topic_handler.rs
server/src/binary/handlers/topics/delete_topic_handler.rs
server/src/binary/handlers/topics/get_topic_handler.rs
server/src/binary/handlers/topics/get_topics_handler.rs
server/src/binary/handlers/topics/update_topic_handler.rs
server/src/http/streams.rs
server/src/http/topics.rs
server/src/streaming/users/permissioner.rs
server/src/streaming/users/permissioner_rules/messages.rs
server/src/streaming/users/permissioner_rules/mod.rs
server/src/streaming/users/permissioner_rules/streams.rs
server/src/streaming/users/permissioner_rules/topics.rs
server/src/streaming/users/permissions.rs
server/tests/streaming_tests/user.rs

Added permissions for all the topic actions, cleaned up permissions struct, updated server to 0.0.5.

Topic permissions

---

Cargo.lock
configs/server.json
configs/server.toml
server/Cargo.toml
server/src/components/logging.rs
server/src/components/mod.rs
server/src/main.rs
server/src/server_error.rs
server/src/streaming/config.rs

Besides that, accordingly modified configs,added
early logging mechanism, filtering based on RUST_LOG and separate Logging component which in future could handle logs retention and cleanup.

Implement logging to file

---

Cargo.lock
bench/src/benchmarks/poll_messages_benchmark.rs
bench/src/benchmarks/send_messages_benchmark.rs
cli/src/main.rs
iggy/Cargo.toml
iggy/src/clients/client.rs
iggy/src/lib.rs
iggy/src/message_handler.rs
samples/src/message-envelope/consumer/main.rs
samples/src/message-envelope/producer/main.rs
samples/src/message-headers/consumer/main.rs
samples/src/message-headers/producer/main.rs
server/src/components/logging.rs
server/tests/server_tests/common/scenarios/consumer_group_join_scenario.rs
server/tests/server_tests/common/scenarios/consumer_group_with_multiple_clients_polling_messages_scenario.rs
server/tests/server_tests/common/scenarios/consumer_group_with_single_client_polling_messages_scenario.rs
server/tests/server_tests/common/scenarios/message_headers_scenario.rs
server/tests/server_tests/common/scenarios/system_scenario.rs
tools/src/data-seeder/main.rs

This component (if provided) will be invoked when polling the messages, or otherwise the previously added `on_message` closure.

Added simple message handler trait as an optional arg for IggyClient

---

server/src/components/logging.rs

Fix build metadata printing at startup

---

Cargo.lock
server/Cargo.toml
server/src/components/config_provider.rs
server/src/server_error.rs
server/tests/config_provider_tests/mod.rs
server/tests/server_tests/common/mod.rs

Fix nested env var config overriding

---

cmd/src/args/message_expire.rs
cmd/src/args/mod.rs
cmd/src/args/topic.rs
cmd/src/cmd/topic/create.rs
cmd/src/cmd/topic/update.rs
cmd/src/main.rs

Move enum MessageExpiry to separate module and add tests

Move MessageExpiry enum to separate module

---

server/src/components/config_provider.rs

Besides that, now server.toml/json is actually used. This fixes #95.

Fix recompilation issue when config.toml is changed

---

.github/workflows/rust.yml
.github/workflows/sanity.yml

Add clippy, rustfmt and semver checks to CI (#72)

---

Cargo.lock
cmd/Cargo.toml
cmd/src/args/mod.rs
cmd/src/args/system.rs
cmd/src/main.rs
iggy/Cargo.toml
iggy/src/cmd/mod.rs
iggy/src/cmd/system/me.rs
iggy/src/cmd/system/mod.rs
iggy/src/cmd/system/ping.rs
iggy/src/cmd/system/stats.rs

Adding system level commands
- ping - to check if server is alive and what's the response time
- me - to check basic client information
- stats - to get iggy server statistics

Add ping, me and stats commands to iggy command line tool

---

server/tests/server_tests/common/mod.rs

Collect iggy-server stdout and stderr in local variables and dump both when any of the test cases fails. Logs can be enabled by setting IGGY_TEST_VERBOSE environment variable.

Collect iggy-server stdout and err in tests and dump in case of errors

---

PULL_REQUEST_TEMPLATE.md

1. Add PR template proposal for Iggy-rs

feat: add pr template

---

Cargo.lock
configs/server.json
configs/server.toml
iggy/src/utils/timestamp.rs
server/Cargo.toml
server/server.http
server/src/configs/http.rs
server/src/http/http_server.rs
server/src/http/jwt.rs
server/src/http/users.rs
server/src/streaming/personal_access_tokens/storage.rs
server/src/streaming/systems/streams.rs
server/src/streaming/systems/system.rs

extend JWT options and validators, fix expiry, closes #186

Revoke JWT, store revoked tokens and remove them periodically

---

server/src/streaming/systems/info.rs

Addresses https://github.com/iggy-rs/iggy/issues/191 
I've one doubt, should we use something like a OnceCell here so that it will cache the first invocation

Use version from Cargo.toml instead of manually hardcoding #191

---

.github/workflows/sanity.yml
server/src/streaming/systems/info.rs

Now warnings will be treated as errors.

Make clippy more restrictive

---

iggy/src/cmd/partitions/create_partitions.rs
iggy/src/cmd/partitions/delete_partitions.rs
integration/tests/cmd/mod.rs
integration/tests/cmd/partition/mod.rs
integration/tests/cmd/partition/test_partition_create_command.rs
integration/tests/cmd/partition/test_partition_delete_command.rs
integration/tests/cmd/partition/test_partition_help_command.rs

Add integration tests for iggy partition commands
Add tests for iggy partition create, delete and help commands and improve commands implementation.

Add integration tests for iggy partition commands

---

configs/server.json
configs/server.toml
integration/tests/streaming/system.rs
server/src/channels/commands/clean_personal_access_tokens.rs
server/src/configs/defaults.rs
server/src/configs/server.rs
server/src/configs/validators.rs
server/src/main.rs
server/src/streaming/systems/personal_access_tokens.rs
server/src/streaming/systems/streams.rs
server/src/streaming/systems/system.rs

for https://github.com/iggy-rs/iggy/issues/181
- Added functions to save, load max personal access token config
- Tested with starting server to confirm both read and write work correctly.
What types of changes does your code introduce to the project? (check at least one)
Before submitting the PR, please make sure you've done the following:

feat: Configurable max personal access token

---

integration/tests/bench/http.rs
integration/tests/bench/mod.rs
integration/tests/bench/quic.rs
integration/tests/bench/tcp.rs
integration/tests/mod.rs

Run iggy-bench in CI

---

integration/tests/streaming/common/test_setup.rs

Use random 128b uuid instead of atomic

Fix toggling tests

---

.github/workflows/sanity.yml

Add cargo sort to CI

---

Cargo.lock
bench/Cargo.toml
cli/Cargo.toml
examples/Cargo.toml
iggy/Cargo.toml
server/Cargo.toml
tools/Cargo.toml

Removed unused dependencies

---

.github/workflows/sanity.yml

Add new check to CI - unused dependencies

---

.github/workflows/ci.yml
.github/workflows/coverage.yml
README.md

Add reporting of coverage to codecov

---

bench/src/server_starter.rs

Detect running server

---

Cargo.lock
bench/Cargo.toml
bench/src/args/simple.rs
bench/src/benchmark_result.rs
bench/src/benchmark_runner.rs
bench/src/benchmarks/send_and_poll_benchmark.rs

Split consumer and producer stats in send_and_poll 
Add human redable values 
This closes https://github.com/iggy-rs/iggy/issues/230.

Improve logging in bench tests 

---

README.md

Add crates.io to README.md

---

.github/ISSUE_TEMPLATE.md
.github/workflows/test_nightly.yml

And create GH issue when it fails.

Move QEMU tests to nightly suite

---

configs/server.toml

Updated the docs inside the server.toml file accordingly to https://docs.iggy.rs/server/configuration and sometimes guesses/suspicions (please validate them) 🙂 
This closes the issue #260.

Document server.toml

---

.github/workflows/test.yml
Cargo.lock
integration/Cargo.toml
integration/tests/cmd/common/command.rs
integration/tests/cmd/common/mod.rs
integration/tests/cmd/general/test_missing_credentials.rs
integration/tests/cmd/partition/test_partition_create_command.rs
integration/tests/cmd/partition/test_partition_delete_command.rs
integration/tests/cmd/personal_access_token/mod.rs
integration/tests/cmd/personal_access_token/test_pat_create_command.rs
integration/tests/cmd/personal_access_token/test_pat_delete_command.rs
integration/tests/cmd/personal_access_token/test_pat_list_command.rs
integration/tests/cmd/personal_access_token/test_pat_login_options.rs
integration/tests/cmd/stream/test_stream_create_command.rs
integration/tests/cmd/stream/test_stream_delete_command.rs
integration/tests/cmd/stream/test_stream_get_command.rs
integration/tests/cmd/stream/test_stream_list_command.rs
integration/tests/cmd/stream/test_stream_update_command.rs
integration/tests/cmd/system/test_me_command.rs
integration/tests/cmd/system/test_ping_command.rs
integration/tests/cmd/system/test_stats_command.rs
integration/tests/cmd/topic/test_topic_create_command.rs
integration/tests/cmd/topic/test_topic_delete_command.rs
integration/tests/cmd/topic/test_topic_get_command.rs
integration/tests/cmd/topic/test_topic_list_command.rs
integration/tests/cmd/topic/test_topic_update_command.rs
integration/tests/cmd/user/mod.rs
integration/tests/cmd/user/test_login_options.rs
integration/tests/cmd/user/test_user_create_command.rs
integration/tests/cmd/user/test_user_delete_command.rs

Add to integration tests test cases which check if iggy cmd properly
connects to iggy server using --username/--password and PAT related
command line options

Add test to check login using cli options

---

.github/workflows/audit.yml
.github/workflows/coverage.yml
.github/workflows/sanity.yml
.github/workflows/test.yml
.github/workflows/test_nightly.yml

Fix creating gh issues when test_nightly fails

---

.github/ISSUE_TEMPLATE.md
.github/workflows/coverage.yml
.github/workflows/release.yml
.github/workflows/test_nightly.yml

Raise a github issue upon failure of coverage or release jobs

---

.github/workflows/release.yml
Cargo.lock
Dockerfile
Dockerfile.ci
server/Cargo.toml

Add iggy-cmd to docker image

---

.github/workflows/publish_sdk.yml
.github/workflows/release.yml

Add automatic cargo publish for SDK

---

Cargo.lock

Because our tests are failing on QEMU ARM.

Revert cargo lock

---

Cargo.lock
iggy/Cargo.toml

Upon merge of this commit, SDK shall be updated to 0.0.123

Test automatic SDK release to crates.io

---

Cargo.lock
iggy/Cargo.toml

To trigger publish to crates.io

Change iggy version in Cargo.toml

---

.github/workflows/test_nightly.yml

Fix bug in test_release.yml

---

Cargo.lock
cmd/Cargo.toml
cmd/src/args/mod.rs
cmd/src/args/partition.rs
cmd/src/args/personal_access_token.rs
cmd/src/args/stream.rs
cmd/src/args/topic.rs
cmd/src/args/user.rs
integration/tests/cmd/general/test_help_command.rs
integration/tests/cmd/general/test_overview_command.rs
integration/tests/cmd/partition/test_partition_help_command.rs
integration/tests/cmd/personal_access_token/test_pat_help_command.rs
integration/tests/cmd/stream/test_stream_help_command.rs
integration/tests/cmd/topic/test_topic_help_command.rs
integration/tests/cmd/user/test_user_help_command.rs

For better user experience add one letter aliases for stream, topic,
partition and user commands and to subcommands.

Add aliases for some commands and subcommands

---

integration/tests/streaming/messages.rs
integration/tests/streaming/segment.rs
integration/tests/streaming/topic_messages.rs

Reverts iggy-rs/iggy#358
It doesn't help to fix our toggling tests.
Deeper investigation is still needed.

Revert "Fix toggling tests"

---

Cargo.lock
configs/server.json
configs/server.toml
iggy/src/utils/duration.rs
server/Cargo.toml
server/src/configs/defaults.rs
server/src/configs/displays.rs
server/src/configs/system.rs
server/src/streaming/deduplication/message_deduplicator.rs
server/src/streaming/deduplication/mod.rs
server/src/streaming/mod.rs
server/src/streaming/partitions/messages.rs
server/src/streaming/partitions/partition.rs
server/src/streaming/partitions/storage.rs

Add time and size based message ID deduplication feature

---

Cargo.lock
bench/Cargo.toml
cli/Cargo.toml
iggy/Cargo.toml
iggy/src/quic/client.rs
server/Cargo.toml
server/src/configs/resource_quota.rs
server/src/configs/validators.rs
server/src/http/diagnostics.rs
server/src/http/http_server.rs
server/src/http/jwt/middleware.rs
server/src/http/metrics.rs
server/src/http/shared.rs
server/src/quic/quic_server.rs
server/src/streaming/cache/memory_tracker.rs
server/src/streaming/systems/stats.rs

Update axum server

---

Cargo.lock
server/Cargo.toml
server/src/streaming/cache/buffer.rs
server/src/streaming/utils/file.rs

use atone instead of VecDeque

---

.github/workflows/test_nightly.yml

This closes #468, #386, #387, #425, #438, #445, #461, #472.

Disable rust debug profile tests in test_nightly suite

---

.github/workflows/sanity.yml
iggy/src/utils/byte_size.rs

Fix coverage problem and add doctest to CI

---

Cargo.lock
cmd/Cargo.toml
cmd/src/args/message.rs
cmd/src/args/mod.rs
cmd/src/main.rs
iggy/Cargo.toml
iggy/src/cmd/message/mod.rs
iggy/src/cmd/message/poll_messages.rs
iggy/src/cmd/message/send_messages.rs
iggy/src/cmd/mod.rs
iggy/src/messages/send_messages.rs
integration/Cargo.toml
integration/tests/cmd/general/test_help_command.rs
integration/tests/cmd/general/test_overview_command.rs
integration/tests/cmd/message/mod.rs
integration/tests/cmd/message/test_message_help_command.rs
integration/tests/cmd/message/test_message_poll_command.rs
integration/tests/cmd/message/test_message_send_command.rs
integration/tests/cmd/mod.rs

Add basic support for message send and message poll commands
to iggy command line client.
Close #428

Add message send and poll commands with integration tests

---

Cargo.lock
server/Cargo.toml
server/server.http
server/src/binary/command.rs
server/src/http/diagnostics.rs
server/src/http/error.rs

Improve error logging

---

.github/workflows/coverage.yml
.github/workflows/test_nightly.yml
integration/Cargo.toml
integration/src/test_server.rs
integration/tests/bench/http.rs
integration/tests/bench/quic.rs
integration/tests/bench/tcp.rs
server/src/http/http_server.rs

Adjust TestServer timeout, fix PR codecov, disable IPv6 tests in CI

---

justfile

- Replace direct test command with aliases for build and test
- Split build and test into separate tasks
- Add tasks for running individual and nextest tests
- Introduce nextest with options for better test output

Refactor justfile with aliases and separate build/test tasks

---

server/src/streaming/systems/streams.rs

Refactor the stream load() function to reduce unnecessary spawn operations during IO and avoid using Arc<Mutex<>>.

Refactor stream loading in System struct

---

server/src/streaming/streams/topics.rs
server/src/streaming/systems/streams.rs

Improve topic ID and stream ID generation on server side

---

Cargo.lock
sdk/Cargo.toml

Update version of strum to 0.26.0

---

Cargo.lock
cli/Cargo.toml
cli/src/args/message.rs
integration/tests/cli/message/test_message_poll_command.rs

Clarify argument descriptions for message poll command
to reflect actual functionality.

Update message polling documentation and version bump

---

integration/tests/config_provider/mod.rs
server/src/configs/config_provider.rs

- Remove unused import from integration tests
- Refactor env var setting in tests for clarity
- Correct assertions to match refactored test variables
- Implement keys_to_env_key function for env var mapping
- Enhance insert_overridden_values_from_env to handle nested keys
- Add debug logging for improved traceability in CustomEnvProvider
- Remove obsolete env var removals in tests
Closes #624.

Fix environment variable handling in config provider

---

README.md

Center link, badges and logo in first paragraph in README.md

Center logo in README

---

server/src/server_error.rs
server/src/tcp/connection_handler.rs

Stop reading TCP stream when causing error.

---

server/src/log/logger.rs

Enhance logging format with thread IDs

---

.github/workflows/backwards_compatibility.yml
.github/workflows/post_release.yml
.github/workflows/sanity.yml

Introduce a new GitHub Actions workflow to ensure that new pull
requests maintain backwards compatibility. The workflow triggers
on PR events and checks commit messages for a 'BREAKING_CHANGE'
keyword to skip tests. It includes steps to build and test both
PR and master branch code.

Add backwards compatibility workflow for PRs

---

bench/src/consumer.rs
integration/tests/bench/http.rs
integration/tests/bench/mod.rs
integration/tests/bench/quic.rs
integration/tests/bench/tcp.rs

Now instead of send and poll, first `send` is called,
and then on same server `poll`.

Improve bench testcases

---

Cargo.lock
bench/Cargo.toml
bench/src/benchmarks/poll_benchmark.rs
bench/src/benchmarks/send_and_poll_benchmark.rs
bench/src/consumer.rs
integration/src/tcp_client.rs
integration/src/test_server.rs
integration/tests/bench/http.rs
integration/tests/bench/mod.rs
integration/tests/bench/quic.rs
integration/tests/bench/tcp.rs
integration/tests/data_integrity/mod.rs
integration/tests/data_integrity/verify_after_server_restart.rs
integration/tests/mod.rs
sdk/src/tcp/client.rs
server/src/binary/handlers/personal_access_tokens/get_personal_access_tokens_handler.rs
server/src/binary/handlers/users/get_user_handler.rs
server/src/binary/handlers/users/get_users_handler.rs
server/src/main.rs
server/src/streaming/cache/memory_tracker.rs
server/src/streaming/partitions/storage.rs
server/src/streaming/segments/messages.rs
server/src/streaming/segments/storage.rs
server/src/streaming/streams/storage.rs
server/src/streaming/systems/users.rs
server/src/streaming/topics/messages.rs

Resolved a bug where messages were not correctly loaded after a server
restart. Enhanced the system's robustness by ensuring accurate message
retrieval post-reboot. Implemented a new integration test to verify
data integrity following server restarts. Improved logging clarity
during the message loading process. Adjusted memory tracking to provide
more precise diagnostics.

Fix server message loading issue on restart and add test case

---

configs/server.json
configs/server.toml
server/Cargo.toml
server/src/build.rs

This commit introduces a standarized check of values for JSON and TOML
server configs, ensuring consistency and readability. Additionally, the
figment and serde_json dependencies have been added to the build script
to facilitate configuration comparison.

Fail compilation if server JSON and TOML configs have different values

---

Cargo.lock
sdk/Cargo.toml
sdk/src/error.rs
sdk/src/identifier.rs

Add TryFrom trait to Identifier

---

Cargo.lock
configs/server.json
configs/server.toml
server/Cargo.toml
server/src/configs/defaults.rs
server/src/configs/displays.rs
server/src/configs/http.rs
server/src/http/http_server.rs

Add setting for max request size in HTTP API

---

server/src/build.rs

The build script has been updated to only compare JSON and TOML
configuration files when the IGGY_CI_BUILD environment variable is set
to 'true'. This ensures that config comparison is part of the CI build
process, reducing unnecessary checks during local development.

Make JSON and TOML configs comparison work only for CI

---

.github/workflows/test_pr.yml
README.md
scripts/run-examples-from-readme.sh

Update CLI examples in README to reflect automatic ID assignment
for streams and topics and optional compression option for topic.
Add a script to run README examples to ensure they work as expected
and include it as a new step in CI.

Update CLI examples in README and add test scenario to CI

---

Cargo.lock
configs/server.json
configs/server.toml
integration/tests/archiver/disk.rs
integration/tests/archiver/mod.rs
integration/tests/archiver/s3.rs
server/Cargo.toml
server/src/archiver/disk.rs
server/src/archiver/mod.rs
server/src/archiver/s3.rs
server/src/channels/commands/archive_state.rs
server/src/configs/displays.rs
server/src/configs/server.rs
server/src/configs/validators.rs
server/src/server_error.rs
server/src/streaming/systems/system.rs

This closes #290 as the second required archiver.

Implement S3 archiver

---

Cargo.lock
cli/Cargo.toml
integration/tests/cli/general/test_help_command.rs
integration/tests/cli/general/test_overview_command.rs
sdk/Cargo.toml

Update integration tests after description update in Cargo.toml

Update crate description and add readme link to main README.md

---

integration/tests/cli/system/test_snapshot_cmd.rs
server/src/configs/displays.rs

Display instance for TcpSocketConfig

---

scripts/performance/run-standard-performance-suite.sh
scripts/performance/utils.sh
scripts/utils.sh

- If server tag is present, use it. Otherise, just return sha1
- If server is not running after 2s, fail script

Improve CI scripts

---

.github/workflows/coverage.yml

Run coverage workflow only when `.rs` files are changed

---

.dockerignore

chore: order values in .dockerignore to test CI

---

Cargo.lock
cli/Cargo.toml

closes https://github.com/iggy-rs/iggy/issues/1458

bump sdk version in cli

---

Cargo.lock
integration/tests/streaming/stream.rs
integration/tests/streaming/topic.rs
server/Cargo.toml
server/src/http/jwt/jwt_manager.rs
server/src/http/jwt/storage.rs
server/src/state/system.rs
server/src/streaming/clients/client_manager.rs
server/src/streaming/streams/storage.rs
server/src/streaming/streams/stream.rs
server/src/streaming/systems/streams.rs
server/src/streaming/systems/system.rs
server/src/streaming/topics/messages.rs
server/src/streaming/topics/storage.rs
server/src/streaming/topics/topic.rs
server/src/streaming/users/user.rs

Instead of HashMap and HashSet, use more performant AHashMap and AHashSet.

Use aHash on the server side

---

.github/workflows/coverage.yml
.github/workflows/sanity.yml
.github/workflows/test_pr.yml

Move coverage workflow under test workflow and change the trigger to
allow users to trigger coverage run directly in GH Actions. Update
sanity workflow step names to show what's run there.

chore(ci): include coverage in test workflow

---

.github/workflows/performance.yml
Cargo.lock
bench/Cargo.toml
bench/report/Cargo.toml
bench/report/src/lib.rs
bench/report/src/plotting/chart.rs
bench/src/actors/consumer.rs
bench/src/benchmarks/consumer_benchmark.rs
bench/src/benchmarks/consumer_group_benchmark.rs
bench/src/benchmarks/producer_and_consumer_benchmark.rs
bench/src/benchmarks/producer_and_consumer_group_benchmark.rs
bench/src/main.rs
bench/src/plot.rs
bench/src/runner.rs
bench/src/utils/cpu_name.rs
bench/src/utils/mod.rs
scripts/performance/run-standard-performance-suite.sh
scripts/performance/utils.sh

This commit introduces several improvements to the benchmark suite:
- Added rate limiting functionality to the consumers.
- Updated the benchmark scripts to include new test scenarios with rate limits.
- Enhanced the output directory naming by appending the CPU name in lowercase.
- Updated dependencies in `Cargo.lock` and `Cargo.toml` to support new features.
- Modified chart creation functions to allow optional title and subtext stripping.
- Refactored scripts to replace large batch tests with normal batch tests.

feat(bench): enhance bench suite

---

Cargo.lock
bench/Cargo.toml
bench/report/Cargo.toml
examples/src/multi-tenant/consumer/main.rs
examples/src/multi-tenant/producer/main.rs
integration/Cargo.toml
sdk/Cargo.toml
server/Cargo.toml
server/src/log/logger.rs

Fix an issue with `HTTP` transport for open telemetry. Additionally, update all dependencies.

fix(server): fix optional HTTP telemetry transport, update dependencies

---

server/src/streaming/systems/snapshot/procdump.rs

fix(server): cargo build fail

---

.github/workflows/backwards_compatibility.yml
.github/workflows/coverage.yml
.github/workflows/post_publish_server.yml
.github/workflows/publish_cli.yml
.github/workflows/publish_sdk.yml
.github/workflows/publish_server.yml
.github/workflows/release_cli.yml
.github/workflows/release_sdk.yml
.github/workflows/release_server.yml
.github/workflows/sanity.yml
.github/workflows/security.yml
.github/workflows/test_daily.yml
.github/workflows/test_nightly.yml
.github/workflows/test_pr.yml

This reverts commit fe7a460ad68e128e4a339283e24e9bc09c0511c7 but
still removes performance.yml.

chore(ci): revert setting GH action to latest versions

---

.github/changed-files-config.json
.github/scripts/analyze_changed_files.py
.github/scripts/detect-changed-files.sh
.github/workflows/ci-check-pr.yml
.github/workflows/ci-prod.yml

Replace GitHub Action which checks changed files with own implementation. Add scripts which implement checks which files has been changed in given pull requests.

chore(ci): replace action which checks changed files

---

Cargo.lock
cli/Cargo.toml
integration/Cargo.toml
server/Cargo.toml
server/src/streaming/partitions/messages.rs
server/src/streaming/systems/users.rs
server/src/tcp/tcp_sender.rs
server/src/tcp/tcp_tls_sender.rs

Fix the `created_at` field for the user, which should be assigned from the state entry timestamp.

fix(server): fix user created at timestamp, update deps

---

.github/scripts/detect-changed-files.sh

chore(ci): Fix ci check pr-file-changes script

---

.convco

chore(ci): add deps scopes for CI PR validation

---

core/examples/src/shared/stream.rs

chore(test): improve consumption message log

---

core/common/src/error/iggy_error.rs
core/common/src/types/configuration/tcp_config/tcp_client_config_builder.rs
core/sdk/src/clients/client_builder.rs

feat(server): verify the format of server_addr

---

.convco

Add `connectors` label to the convco commit message validator.

chore(repo): add connectors to convco commit validator

---

foreign/node/src/e2e/tcp.consumer-group.e2e.ts
foreign/node/src/e2e/tcp.consumer-stream.e2e.ts
foreign/node/src/e2e/tcp.send-message.e2e.ts
foreign/node/src/wire/message/iggy-header.utils.ts
foreign/node/src/wire/message/poll.utils.ts

fix silent poll message deserialization bug

fix(js): fix deserializePollMessages bug

---

foreign/java/java-sdk/build.gradle.kts

Configure gradle to publish artifacts to Apache maven repo.
Fixes #1868 
FYI: Created [INFRA-26910](https://issues.apache.org/jira/browse/INFRA-26910) to get Nexus access.

chore(sdk): Java SDK - publish artifacts to apache maven repo

---

.github/workflows/publish_java_sdk.yml

chore(ci): publish java-sdk to maven

---

foreign/node/src/bdd/message.ts
foreign/node/src/tcp.sm.utils.ts
foreign/node/src/wire/message/iggy-header.utils.ts
foreign/node/src/wire/message/message.utils.ts
foreign/node/src/wire/message/send-messages.command.test.ts
foreign/node/src/wire/number.utils.ts

return polled messages id as Bigint instead of uuid string

feat(js): return message id as bigint instead of uuid string

---

.github/workflows/publish_java_sdk.yml
.github/workflows/publish_java_sdk_snapshots.yml
foreign/java/java-sdk/build.gradle.kts

chore(ci): java-sdk export nexus username and password as env

---

Cargo.lock
core/server/Cargo.toml
core/server/src/bootstrap.rs
core/server/src/main.rs
core/server/src/shard/builder.rs
core/server/src/shard/mod.rs
core/server/src/shard/task_registry.rs
core/server/src/shard/tasks/messages.rs
core/server/src/tcp/connection_handler.rs
core/server/src/tcp/tcp_listener.rs
core/server/src/tcp/tcp_server.rs

feat(tpc): implement cooperative shutdown

---

README.md

chore(docs): Improve grammar and wording in README.md

---

bdd/go/tests/tcp_test/messages_steps.go
foreign/go/binary_serialization/fetch_messages_request_serializer_test.go
foreign/go/contracts/consumer.go
foreign/go/samples/consumer/consumer.go

add `DefaultConsumer` , `NewSingleConsuemr`, `NewGroupConsuemr` for `iggcon.Consumer`, to align with rust sdk.

feat(sdk): add some construct function for iggcon.Consumer to align with rust sdk

---

bdd/go/tests/tcp_test/messages_feature_send.go
foreign/go/contracts/partitions.go

change PartitionId argument type to uint32

refactor(sdk): change PartitionId argument type to uint32

---

foreign/java/examples/simple-consumer/build.gradle.kts
foreign/java/examples/simple-producer/build.gradle.kts
foreign/java/java-sdk/build.gradle.kts

chore(sdk): support artifact signing in java-sdk

---

bdd/go/tests/tcp_test/stream_feature_get_by_id.go
foreign/go/binary_serialization/binary_response_deserializer.go
foreign/go/tcp/tcp_stream_managament.go

What I did
1. implement deserialize topics logic in `DeserializeStream` function
2. add test for it

feat(go): implement deserialize topics logic in DeserializeStream function

---

Cargo.lock
Cargo.toml
core/sdk/src/tcp/tcp_tls_verifier.rs
core/server/Cargo.toml
core/server/src/binary/sender.rs
core/server/src/tcp/tcp_server.rs
core/server/src/tcp/tcp_tls_listener.rs
core/server/src/tcp/tcp_tls_sender.rs

Fixes: https://github.com/apache/iggy/issues/1936
Migrates the  TCP TLS listener and sender from tokio based `tokio-tls` with `compio-tls` to align with the project's io_uring migration strategy

fix(server): Update TCP TLS server with compio.
